"use strict";
// ==============================================================================
// content.js — vocabulary + sentence data. Owns: WORD_POOL, SENTENCE_POOL,
// BLANKS_BY_POS, SENTENCE_WORDS, CONJ_PERSONS, CONJ_POOL. Edit here to add/adjust
// vocab, sentences and verb paradigms.
// ==============================================================================

// ---------------------------------------------------------------------------
// Word pool — the A1 (beginner) Italian vocabulary, drawn in order and cycled.
// Each entry pairs the Italian word (`it`, shown in the circle) with its German
// meaning (`de`). Nouns keep their article in both languages so the learner
// absorbs gender; verbs are given as infinitives, everything else in its base
// form. Grouped by theme for upkeep; the game treats it as one flat list.
//
// Where the A1 scope comes from
// -----------------------------
// The pool covers the official A1 lexical inventory of the *Profilo della lingua
// italiana. Livelli del QCER A1, A2, B1, B2* (Spinelli & Parizzi 2010) — the
// CEFR reference-level description for Italian, published by the CVCL of the
// Università per Stranieri di Perugia. Its A1 list is 486 lemmas:
//   https://www.unistrapg.it/profilo_lingua_italiana/site/liste_lessicali_a1.html
// All 486 are represented here, with two deliberate exceptions: the bare
// definite articles (il, lo, la, i, gli, le) and the indefinite un/o/a. Seven
// cards that all answer "der/die/das" teach nothing and cannot be marked right —
// Italian gender is taught the way it is actually used, by the article each noun
// below carries. Everything beyond the 486 is extra the game already had (more
// animals, body parts, colours, numbers); it is kept, not pruned.
//
// …and the practical layer on top of it
// -------------------------------------
// A syllabus list is not the same as what people say. So the pool also carries
// everyday phrases ("come stai?", "quanto costa?", "mi dispiace"), the discourse
// glue that joins spoken sentences (allora, quindi, però, magari, purtroppo),
// the high-frequency verbs the A1 list skips (chiedere, credere, riuscire,
// conoscere) and the abstractions that fill ordinary talk (la gente, la volta,
// il modo). These were checked against the *Nuovo vocabolario di base della
// lingua italiana* (De Mauro & Chiari 2016) through dizionario.internazionale.it:
// all but a few carry the FO mark — the ~2000 lemmas that make up 86% of
// everything written or spoken in Italian.
//
// Two things to respect when adding a phrase. `normAnswer` in quiz.js turns an
// apostrophe into a space, so a German gloss must not contain one ("wie geht es
// dir?", never "wie geht's?") or nobody can type it. And the rune circle draws
// each word as one un-wrapped SVG <text> in a 48px-radius bubble, so anything
// much past ~16 characters starts to hang over the edge.
//
// To re-check coverage after editing, diff the `it` fields (minus their article)
// against that page's numbered list.
// ---------------------------------------------------------------------------
const WORD_POOL = [
  // Greetings & courtesy
  { it: "ciao", de: "hallo" },
  { it: "buongiorno", de: "guten Morgen" },
  { it: "buonasera", de: "guten Abend" },
  { it: "buonanotte", de: "gute Nacht" },
  { it: "arrivederci", de: "auf Wiedersehen" },
  { it: "grazie", de: "danke" },
  { it: "prego", de: "gern geschehen" },
  { it: "per favore", de: "bitte" },
  { it: "scusa", de: "Entschuldigung" },
  { it: "sì", de: "ja" },
  { it: "l'affetto", de: "die Zuneigung" },
  { it: "l'augurio", de: "der Glückwunsch" },
  { it: "il saluto", de: "der Gruß" },
  { it: "il bacio", de: "der Kuss" },
  { it: "l'attenzione", de: "die Aufmerksamkeit" },
  { it: "il favore", de: "der Gefallen" },
  { it: "il piacere", de: "das Vergnügen" },
  { it: "la cosa", de: "die Sache" },
  { it: "aiuto", de: "Hilfe" },
  { it: "cin cin", de: "Prost" },
  { it: "salute", de: "Gesundheit" },

  // Everyday phrases — the chunks a beginner actually says out loud
  { it: "come stai?", de: "wie geht es dir?" },
  { it: "come va?", de: "wie läuft es?" },
  { it: "va bene", de: "in Ordnung" },
  { it: "d'accordo", de: "einverstanden" },
  { it: "mi dispiace", de: "es tut mir leid" },
  { it: "non capisco", de: "ich verstehe nicht" },
  { it: "non lo so", de: "ich weiß es nicht" },
  { it: "quanto costa?", de: "was kostet das?" },
  { it: "quanti anni hai?", de: "wie alt bist du?" },
  { it: "mi chiamo", de: "ich heiße" },
  { it: "di niente", de: "keine Ursache" },
  { it: "a presto", de: "bis bald" },
  { it: "a domani", de: "bis morgen" },
  { it: "buon appetito", de: "guten Appetit" },
  { it: "buona fortuna", de: "viel Glück" },
  { it: "che peccato", de: "wie schade" },
  { it: "posso?", de: "darf ich?" },
  { it: "vorrei", de: "ich hätte gern" },
  { it: "ecco", de: "hier ist" },
  { it: "basta", de: "genug" },

  // People & family
  { it: "la famiglia", de: "die Familie" },
  { it: "la madre", de: "die Mutter" },
  { it: "il padre", de: "der Vater" },
  { it: "il figlio", de: "der Sohn" },
  { it: "la figlia", de: "die Tochter" },
  { it: "il fratello", de: "der Bruder" },
  { it: "la sorella", de: "die Schwester" },
  { it: "il nonno", de: "der Großvater" },
  { it: "la nonna", de: "die Großmutter" },
  { it: "il bambino", de: "das Kind" },
  { it: "l'uomo", de: "der Mann" },
  { it: "la donna", de: "die Frau" },
  { it: "l'amico", de: "der Freund" },
  { it: "il ragazzo", de: "der Junge" },
  { it: "la ragazza", de: "das Mädchen" },
  { it: "il nome", de: "der Name" },
  { it: "la mamma", de: "die Mama" },
  { it: "il papà", de: "der Papa" },
  { it: "il marito", de: "der Ehemann" },
  { it: "la moglie", de: "die Ehefrau" },
  { it: "maschio", de: "männlich" },
  { it: "femmina", de: "weiblich" },
  { it: "il compagno", de: "der Partner" },
  { it: "la signora", de: "die Dame" },
  { it: "il dottore", de: "der Arzt" },
  { it: "il professore", de: "der Lehrer" },
  { it: "l'insegnante", de: "die Lehrkraft" },
  { it: "lo studente", de: "der Student" },
  { it: "il turista", de: "der Tourist" },
  { it: "il cameriere", de: "der Kellner" },

  // Body
  { it: "la testa", de: "der Kopf" },
  { it: "la faccia", de: "das Gesicht" },
  { it: "la mano", de: "die Hand" },
  { it: "il piede", de: "der Fuß" },
  { it: "l'occhio", de: "das Auge" },
  { it: "la bocca", de: "der Mund" },
  { it: "il naso", de: "die Nase" },
  { it: "l'orecchio", de: "das Ohr" },
  { it: "il braccio", de: "der Arm" },
  { it: "la gamba", de: "das Bein" },
  { it: "il cuore", de: "das Herz" },
  { it: "i capelli", de: "die Haare" },
  { it: "il dente", de: "der Zahn" },
  { it: "gli occhiali", de: "die Brille" },
  { it: "la medicina", de: "die Medizin" },
  { it: "il sonno", de: "der Schlaf" },

  // Food & drink
  { it: "il cibo", de: "das Essen" },
  { it: "il pane", de: "das Brot" },
  { it: "l'acqua", de: "das Wasser" },
  { it: "il vino", de: "der Wein" },
  { it: "il latte", de: "die Milch" },
  { it: "il caffè", de: "der Kaffee" },
  { it: "il tè", de: "der Tee" },
  { it: "la birra", de: "das Bier" },
  { it: "la frutta", de: "das Obst" },
  { it: "la mela", de: "der Apfel" },
  { it: "l'arancia", de: "die Orange" },
  { it: "il formaggio", de: "der Käse" },
  { it: "la carne", de: "das Fleisch" },
  { it: "il pesce", de: "der Fisch" },
  { it: "l'uovo", de: "das Ei" },
  { it: "il riso", de: "der Reis" },
  { it: "il sale", de: "das Salz" },
  { it: "lo zucchero", de: "der Zucker" },
  { it: "la verdura", de: "das Gemüse" },
  { it: "il pollo", de: "das Hähnchen" },
  { it: "il gelato", de: "das Eis" },
  { it: "il burro", de: "die Butter" },
  { it: "il dolce", de: "der Nachtisch" },
  { it: "la colazione", de: "das Frühstück" },
  { it: "il pranzo", de: "das Mittagessen" },
  { it: "la cena", de: "das Abendessen" },
  { it: "l'aceto", de: "der Essig" },
  { it: "l'olio", de: "das Öl" },
  { it: "il pepe", de: "der Pfeffer" },
  { it: "il pomodoro", de: "die Tomate" },
  { it: "la pasta", de: "die Nudeln" },
  { it: "gli spaghetti", de: "die Spaghetti" },
  { it: "la pizza", de: "die Pizza" },
  { it: "il cappuccino", de: "der Cappuccino" },
  { it: "la fame", de: "der Hunger" },
  { it: "la sete", de: "der Durst" },

  // Table & restaurant
  { it: "la bottiglia", de: "die Flasche" },
  { it: "il bicchiere", de: "das Glas" },
  { it: "il coltello", de: "das Messer" },
  { it: "la forchetta", de: "die Gabel" },
  { it: "il cucchiaio", de: "der Löffel" },
  { it: "il piatto", de: "der Teller" },
  { it: "il menù", de: "die Speisekarte" },
  { it: "il conto", de: "die Rechnung" },

  // Animals
  { it: "il gatto", de: "die Katze" },
  { it: "il cane", de: "der Hund" },
  { it: "il cavallo", de: "das Pferd" },
  { it: "l'uccello", de: "der Vogel" },
  { it: "la mucca", de: "die Kuh" },
  { it: "il topo", de: "die Maus" },
  { it: "il maiale", de: "das Schwein" },
  { it: "la pecora", de: "das Schaf" },

  // Home & objects
  { it: "la casa", de: "das Haus" },
  { it: "la porta", de: "die Tür" },
  { it: "la finestra", de: "das Fenster" },
  { it: "la sedia", de: "der Stuhl" },
  { it: "il tavolo", de: "der Tisch" },
  { it: "il letto", de: "das Bett" },
  { it: "la cucina", de: "die Küche" },
  { it: "il bagno", de: "das Badezimmer" },
  { it: "la camera", de: "das Zimmer" },
  { it: "la chiave", de: "der Schlüssel" },
  { it: "il libro", de: "das Buch" },
  { it: "la penna", de: "der Stift" },
  { it: "la carta", de: "das Papier" },
  { it: "la lampada", de: "die Lampe" },
  { it: "lo specchio", de: "der Spiegel" },
  { it: "il telefono", de: "das Telefon" },
  { it: "l'orologio", de: "die Uhr" },
  { it: "l'appartamento", de: "die Wohnung" },
  { it: "il giardino", de: "der Garten" },
  { it: "la doccia", de: "die Dusche" },
  { it: "il soggiorno", de: "das Wohnzimmer" },
  { it: "il piano", de: "die Etage" },
  { it: "il quadro", de: "das Bild" },
  { it: "la pianta", de: "die Pflanze" },
  { it: "l'ombrello", de: "der Schirm" },
  { it: "la matita", de: "der Bleistift" },
  { it: "il quaderno", de: "das Heft" },
  { it: "la sigaretta", de: "die Zigarette" },
  { it: "l'animale", de: "das Tier" },

  // Clothes
  { it: "il vestito", de: "das Kleid" },
  { it: "la scarpa", de: "der Schuh" },
  { it: "il cappello", de: "der Hut" },
  { it: "la giacca", de: "die Jacke" },
  { it: "i pantaloni", de: "die Hose" },
  { it: "la camicia", de: "das Hemd" },
  { it: "la borsa", de: "die Tasche" },
  { it: "la calza", de: "die Socke" },
  { it: "la gonna", de: "der Rock" },
  { it: "la maglietta", de: "das T-Shirt" },
  { it: "il maglione", de: "der Pullover" },
  { it: "il cappotto", de: "der Mantel" },

  // Nature
  { it: "il sole", de: "die Sonne" },
  { it: "la luna", de: "der Mond" },
  { it: "la stella", de: "der Stern" },
  { it: "il cielo", de: "der Himmel" },
  { it: "il mare", de: "das Meer" },
  { it: "la montagna", de: "der Berg" },
  { it: "il fiume", de: "der Fluss" },
  { it: "l'albero", de: "der Baum" },
  { it: "il fiore", de: "die Blume" },
  { it: "la pioggia", de: "der Regen" },
  { it: "la neve", de: "der Schnee" },
  { it: "il vento", de: "der Wind" },
  { it: "il fuoco", de: "das Feuer" },
  { it: "la terra", de: "die Erde" },
  { it: "il bosco", de: "der Wald" },
  { it: "la spiaggia", de: "der Strand" },

  // Time
  { it: "il giorno", de: "der Tag" },
  { it: "la notte", de: "die Nacht" },
  { it: "la mattina", de: "der Morgen" },
  { it: "la sera", de: "der Abend" },
  { it: "la settimana", de: "die Woche" },
  { it: "il mese", de: "der Monat" },
  { it: "l'anno", de: "das Jahr" },
  { it: "l'ora", de: "die Stunde" },
  { it: "il tempo", de: "die Zeit" },
  { it: "oggi", de: "heute" },
  { it: "domani", de: "morgen" },
  { it: "ieri", de: "gestern" },
  { it: "adesso", de: "jetzt" },
  { it: "sempre", de: "immer" },
  { it: "mai", de: "nie" },
  { it: "presto", de: "früh" },
  { it: "tardi", de: "spät" },
  { it: "il minuto", de: "die Minute" },
  { it: "il secondo", de: "die Sekunde" },
  { it: "il quarto", de: "das Viertel" },
  { it: "la metà", de: "die Hälfte" },
  { it: "il mezzogiorno", de: "der Mittag" },
  { it: "la mezzanotte", de: "die Mitternacht" },
  { it: "il pomeriggio", de: "der Nachmittag" },
  { it: "la giornata", de: "der ganze Tag" },

  // Days of the week
  { it: "lunedì", de: "Montag" },
  { it: "martedì", de: "Dienstag" },
  { it: "mercoledì", de: "Mittwoch" },
  { it: "giovedì", de: "Donnerstag" },
  { it: "venerdì", de: "Freitag" },
  { it: "sabato", de: "Samstag" },
  { it: "domenica", de: "Sonntag" },

  // Months
  { it: "gennaio", de: "Januar" },
  { it: "febbraio", de: "Februar" },
  { it: "marzo", de: "März" },
  { it: "aprile", de: "April" },
  { it: "maggio", de: "Mai" },
  { it: "giugno", de: "Juni" },
  { it: "luglio", de: "Juli" },
  { it: "agosto", de: "August" },
  { it: "settembre", de: "September" },
  { it: "ottobre", de: "Oktober" },
  { it: "novembre", de: "November" },
  { it: "dicembre", de: "Dezember" },

  // Seasons & holidays
  { it: "la primavera", de: "der Frühling" },
  { it: "l'estate", de: "der Sommer" },
  { it: "l'autunno", de: "der Herbst" },
  { it: "l'inverno", de: "der Winter" },
  { it: "Natale", de: "Weihnachten" },
  { it: "Pasqua", de: "Ostern" },

  // Colours
  { it: "rosso", de: "rot" },
  { it: "blu", de: "blau" },
  { it: "verde", de: "grün" },
  { it: "giallo", de: "gelb" },
  { it: "nero", de: "schwarz" },
  { it: "bianco", de: "weiß" },
  { it: "grigio", de: "grau" },
  { it: "rosa", de: "rosa" },
  { it: "arancione", de: "orange" },
  { it: "marrone", de: "braun" },

  // Numbers
  { it: "uno", de: "eins" },
  { it: "due", de: "zwei" },
  { it: "tre", de: "drei" },
  { it: "quattro", de: "vier" },
  { it: "cinque", de: "fünf" },
  { it: "sei", de: "sechs" },
  { it: "sette", de: "sieben" },
  { it: "otto", de: "acht" },
  { it: "nove", de: "neun" },
  { it: "dieci", de: "zehn" },

  // Adjectives
  { it: "grande", de: "groß" },
  { it: "piccolo", de: "klein" },
  { it: "buono", de: "gut" },
  { it: "cattivo", de: "schlecht" },
  { it: "bello", de: "schön" },
  { it: "brutto", de: "hässlich" },
  { it: "nuovo", de: "neu" },
  { it: "vecchio", de: "alt" },
  { it: "caldo", de: "heiß" },
  { it: "freddo", de: "kalt" },
  { it: "alto", de: "hoch" },
  { it: "basso", de: "niedrig" },
  { it: "lungo", de: "lang" },
  { it: "corto", de: "kurz" },
  { it: "facile", de: "einfach" },
  { it: "difficile", de: "schwierig" },
  { it: "felice", de: "glücklich" },
  { it: "triste", de: "traurig" },
  { it: "veloce", de: "schnell" },
  { it: "lento", de: "langsam" },
  { it: "forte", de: "stark" },
  { it: "debole", de: "schwach" },
  { it: "giovane", de: "jung" },
  { it: "ricco", de: "reich" },
  { it: "povero", de: "arm" },
  { it: "pieno", de: "voll" },
  { it: "vuoto", de: "leer" },
  { it: "pulito", de: "sauber" },
  { it: "sporco", de: "schmutzig" },
  { it: "attento", de: "aufmerksam" },
  { it: "biondo", de: "blond" },
  { it: "caro", de: "teuer" },
  { it: "castano", de: "braunhaarig" },
  { it: "doppio", de: "doppelt" },
  { it: "falso", de: "falsch" },
  { it: "gentile", de: "freundlich" },
  { it: "importante", de: "wichtig" },
  { it: "intelligente", de: "intelligent" },
  { it: "interessante", de: "interessant" },
  { it: "internazionale", de: "international" },
  { it: "largo", de: "breit" },
  { it: "magro", de: "dünn" },
  { it: "malato", de: "krank" },
  { it: "mezzo", de: "halb" },
  { it: "simpatico", de: "sympathisch" },
  { it: "singolo", de: "einzeln" },
  { it: "stanco", de: "müde" },
  { it: "straniero", de: "ausländisch" },
  { it: "stretto", de: "eng" },
  { it: "vero", de: "wahr" },
  { it: "bravo", de: "tüchtig" },
  { it: "mio", de: "mein" },
  { it: "tuo", de: "dein" },
  { it: "quello", de: "jener" },
  { it: "questo", de: "dieser" },

  // Verbs
  { it: "essere", de: "sein" },
  { it: "avere", de: "haben" },
  { it: "fare", de: "machen" },
  { it: "andare", de: "gehen" },
  { it: "venire", de: "kommen" },
  { it: "stare", de: "bleiben" },
  { it: "mangiare", de: "essen" },
  { it: "bere", de: "trinken" },
  { it: "dormire", de: "schlafen" },
  { it: "parlare", de: "sprechen" },
  { it: "dire", de: "sagen" },
  { it: "leggere", de: "lesen" },
  { it: "scrivere", de: "schreiben" },
  { it: "vedere", de: "sehen" },
  { it: "sentire", de: "hören" },
  { it: "capire", de: "verstehen" },
  { it: "sapere", de: "wissen" },
  { it: "volere", de: "wollen" },
  { it: "potere", de: "können" },
  { it: "dovere", de: "müssen" },
  { it: "vivere", de: "leben" },
  { it: "amare", de: "lieben" },
  { it: "giocare", de: "spielen" },
  { it: "lavorare", de: "arbeiten" },
  { it: "studiare", de: "lernen" },
  { it: "comprare", de: "kaufen" },
  { it: "aprire", de: "öffnen" },
  { it: "chiudere", de: "schließen" },
  { it: "guardare", de: "schauen" },
  { it: "ascoltare", de: "zuhören" },
  { it: "camminare", de: "laufen" },
  { it: "correre", de: "rennen" },
  { it: "pensare", de: "denken" },
  { it: "prendere", de: "nehmen" },
  { it: "dare", de: "geben" },
  { it: "trovare", de: "finden" },
  { it: "chiamare", de: "rufen" },
  { it: "aspettare", de: "warten" },
  { it: "arrivare", de: "ankommen" },
  { it: "partire", de: "abfahren" },
  { it: "pagare", de: "bezahlen" },
  { it: "cucinare", de: "kochen" },
  // -isc- verbs (and one more irregular): they earn their place in the pool by
  // being the patterns the conjugation drills below need more than one example of
  { it: "finire", de: "beenden" },
  { it: "preferire", de: "bevorzugen" },
  { it: "pulire", de: "putzen" },
  { it: "uscire", de: "hinausgehen" },
  { it: "abitare", de: "wohnen" },
  { it: "ballare", de: "tanzen" },
  { it: "cambiare", de: "wechseln" },
  { it: "cantare", de: "singen" },
  { it: "cenare", de: "zu Abend essen" },
  { it: "cercare", de: "suchen" },
  { it: "cominciare", de: "anfangen" },
  { it: "costare", de: "kosten" },
  { it: "domandare", de: "fragen" },
  { it: "entrare", de: "eintreten" },
  { it: "fumare", de: "rauchen" },
  { it: "imparare", de: "lernen" },
  { it: "incontrare", de: "treffen" },
  { it: "insegnare", de: "unterrichten" },
  { it: "mettere", de: "legen" },
  { it: "morire", de: "sterben" },
  { it: "nascere", de: "geboren werden" },
  { it: "piovere", de: "regnen" },
  { it: "portare", de: "tragen" },
  { it: "pranzare", de: "zu Mittag essen" },
  { it: "prenotare", de: "reservieren" },
  { it: "ripetere", de: "wiederholen" },
  { it: "rispondere", de: "antworten" },
  { it: "ritornare", de: "zurückkehren" },
  { it: "scusare", de: "entschuldigen" },
  { it: "significare", de: "bedeuten" },
  { it: "spedire", de: "verschicken" },
  { it: "sposare", de: "heiraten" },
  { it: "suonare", de: "spielen" },
  { it: "svegliarsi", de: "aufwachen" },
  { it: "telefonare", de: "anrufen" },
  { it: "tornare", de: "zurückkommen" },
  { it: "viaggiare", de: "reisen" },
  { it: "visitare", de: "besuchen" },
  { it: "vedersi", de: "sich sehen" },
  { it: "piacere", de: "gefallen" },

  // More of the verbs that carry ordinary talk
  { it: "chiedere", de: "bitten" },
  { it: "credere", de: "glauben" },
  { it: "sperare", de: "hoffen" },
  { it: "ricordare", de: "erinnern" },
  { it: "dimenticare", de: "vergessen" },
  { it: "provare", de: "versuchen" },
  { it: "usare", de: "benutzen" },
  { it: "aiutare", de: "helfen" },
  { it: "lasciare", de: "lassen" },
  { it: "tenere", de: "halten" },
  { it: "perdere", de: "verlieren" },
  { it: "vincere", de: "gewinnen" },
  { it: "succedere", de: "geschehen" },
  { it: "funzionare", de: "funktionieren" },
  { it: "diventare", de: "werden" },
  { it: "sembrare", de: "scheinen" },
  { it: "restare", de: "übrig bleiben" },
  { it: "servire", de: "dienen" },
  { it: "riuscire", de: "schaffen" },
  { it: "conoscere", de: "kennen" },

  // Places
  { it: "la città", de: "die Stadt" },
  { it: "il paese", de: "das Land" },
  { it: "la strada", de: "die Straße" },
  { it: "la scuola", de: "die Schule" },
  { it: "il negozio", de: "das Geschäft" },
  { it: "il ristorante", de: "das Restaurant" },
  { it: "l'ospedale", de: "das Krankenhaus" },
  { it: "la stazione", de: "der Bahnhof" },
  { it: "l'aeroporto", de: "der Flughafen" },
  { it: "la banca", de: "die Bank" },
  { it: "il parco", de: "der Park" },
  { it: "la chiesa", de: "die Kirche" },
  { it: "il mercato", de: "der Markt" },
  { it: "l'ufficio", de: "das Büro" },
  { it: "il museo", de: "das Museum" },
  { it: "la piazza", de: "der Platz" },
  { it: "l'albergo", de: "das Hotel" },
  { it: "l'hotel", de: "die Herberge" },
  { it: "il bar", de: "die Bar" },
  { it: "il cinema", de: "das Kino" },
  { it: "il teatro", de: "das Theater" },
  { it: "la pizzeria", de: "die Pizzeria" },
  { it: "il supermercato", de: "der Supermarkt" },
  { it: "la farmacia", de: "die Apotheke" },
  { it: "la posta", de: "die Post" },
  { it: "l'agenzia", de: "die Agentur" },
  { it: "l'ambasciata", de: "die Botschaft" },
  { it: "il consolato", de: "das Konsulat" },
  { it: "la polizia", de: "die Polizei" },
  { it: "l'università", de: "die Universität" },
  { it: "la fabbrica", de: "die Fabrik" },
  { it: "l'industria", de: "die Industrie" },
  { it: "il centro", de: "das Zentrum" },
  { it: "il parcheggio", de: "der Parkplatz" },
  { it: "la fermata", de: "die Haltestelle" },
  { it: "la via", de: "der Weg" },
  { it: "il lago", de: "der See" },
  { it: "la campagna", de: "das Land" },
  { it: "l'estero", de: "das Ausland" },
  { it: "il posto", de: "der Ort" },

  // Transport
  { it: "la macchina", de: "das Auto" },
  { it: "il treno", de: "der Zug" },
  { it: "l'autobus", de: "der Bus" },
  { it: "la bicicletta", de: "das Fahrrad" },
  { it: "l'aereo", de: "das Flugzeug" },
  { it: "la nave", de: "das Schiff" },

  // Travel & documents
  { it: "il viaggio", de: "die Reise" },
  { it: "la vacanza", de: "der Urlaub" },
  { it: "il biglietto", de: "die Fahrkarte" },
  { it: "il passaporto", de: "der Reisepass" },
  { it: "il documento", de: "das Dokument" },
  { it: "il visto", de: "das Visum" },
  { it: "il check-in", de: "der Check-in" },
  { it: "la moto", de: "das Motorrad" },
  { it: "il taxi", de: "das Taxi" },
  { it: "lo stop", de: "das Stoppschild" },
  { it: "la valigia", de: "der Koffer" },
  { it: "lo zaino", de: "der Rucksack" },

  // Everyday life
  { it: "il lavoro", de: "die Arbeit" },
  { it: "i soldi", de: "das Geld" },
  { it: "il regalo", de: "das Geschenk" },
  { it: "la festa", de: "die Party" },
  { it: "la musica", de: "die Musik" },
  { it: "il film", de: "der Film" },
  { it: "la parola", de: "das Wort" },
  { it: "la lingua", de: "die Sprache" },
  { it: "il numero", de: "die Zahl" },
  { it: "la domanda", de: "die Frage" },
  { it: "la risposta", de: "die Antwort" },
  { it: "il problema", de: "das Problem" },
  { it: "l'idea", de: "die Idee" },
  { it: "la vita", de: "das Leben" },
  { it: "l'amore", de: "die Liebe" },
  { it: "la storia", de: "die Geschichte" },
  { it: "il colore", de: "die Farbe" },

  // Communication & media
  { it: "il computer", de: "der Computer" },
  { it: "il cellulare", de: "das Handy" },
  { it: "la tv", de: "der Fernseher" },
  { it: "la televisione", de: "das Fernsehen" },
  { it: "la radio", de: "das Radio" },
  { it: "il cd", de: "die CD" },
  { it: "il fax", de: "das Fax" },
  { it: "l'e-mail", de: "die E-Mail" },
  { it: "internet", de: "das Internet" },
  { it: "la lettera", de: "der Brief" },
  { it: "la cartolina", de: "die Postkarte" },
  { it: "il francobollo", de: "die Briefmarke" },
  { it: "il giornale", de: "die Zeitung" },
  { it: "la fotografia", de: "das Foto" },
  { it: "la busta", de: "der Umschlag" },
  { it: "il pacco", de: "das Paket" },

  // School, study & leisure
  { it: "la lezione", de: "die Lektion" },
  { it: "la classe", de: "die Klasse" },
  { it: "il corso", de: "der Kurs" },
  { it: "l'esercizio", de: "die Übung" },
  { it: "l'alfabeto", de: "das Alphabet" },
  { it: "italiano", de: "Italienisch" },
  { it: "l'arte", de: "die Kunst" },
  { it: "lo sport", de: "der Sport" },
  { it: "l'hobby", de: "das Hobby" },
  { it: "la canzone", de: "das Lied" },

  // Money & shopping
  { it: "il prezzo", de: "der Preis" },
  { it: "l'euro", de: "der Euro" },
  { it: "la spesa", de: "der Einkauf" },
  { it: "il credito", de: "das Guthaben" },

  // Personal data & appointments
  { it: "il cognome", de: "der Nachname" },
  { it: "l'indirizzo", de: "die Adresse" },
  { it: "la nazionalità", de: "die Staatsangehörigkeit" },
  { it: "la nazione", de: "die Nation" },
  { it: "la data", de: "das Datum" },
  { it: "il compleanno", de: "der Geburtstag" },
  { it: "l'informazione", de: "die Information" },
  { it: "la segreteria", de: "das Sekretariat" },
  { it: "l'appuntamento", de: "der Termin" },
  { it: "il momento", de: "der Moment" },

  // Everyday abstractions
  { it: "la gente", de: "die Leute" },
  { it: "la volta", de: "das Mal" },
  { it: "il modo", de: "die Art" },
  { it: "la parte", de: "der Teil" },
  { it: "il fatto", de: "die Tatsache" },
  { it: "il caso", de: "der Fall" },
  { it: "il motivo", de: "der Grund" },
  { it: "il bisogno", de: "das Bedürfnis" },
  { it: "il pezzo", de: "das Stück" },
  { it: "il gruppo", de: "die Gruppe" },
  { it: "il punto", de: "der Punkt" },
  { it: "la ragione", de: "das Recht" },
  { it: "l'esempio", de: "das Beispiel" },
  { it: "la paura", de: "die Angst" },
  { it: "la fretta", de: "die Eile" },
  { it: "la fine", de: "das Ende" },

  // Question & function words
  { it: "chi", de: "wer" },
  { it: "che", de: "was" },
  { it: "dove", de: "wo" },
  { it: "quando", de: "wann" },
  { it: "perché", de: "warum" },
  { it: "come", de: "wie" },
  { it: "quanto", de: "wie viel" },
  { it: "molto", de: "sehr" },
  { it: "poco", de: "wenig" },
  { it: "tutto", de: "alles" },
  { it: "niente", de: "nichts" },
  { it: "qui", de: "hier" },
  { it: "là", de: "dort" },
  { it: "bene", de: "gut" },
  { it: "male", de: "schlecht" },
  { it: "anche", de: "auch" },
  { it: "ma", de: "aber" },
  { it: "con", de: "mit" },
  { it: "senza", de: "ohne" },
  { it: "sotto", de: "unter" },
  { it: "sopra", de: "über" },
  { it: "dentro", de: "drinnen" },
  { it: "fuori", de: "draußen" },
  { it: "vicino", de: "nah" },
  { it: "lontano", de: "weit" },
  { it: "a", de: "zu" },
  { it: "di", de: "von" },
  { it: "in", de: "in" },
  { it: "per", de: "für" },
  { it: "e", de: "und" },
  { it: "o", de: "oder" },
  { it: "no", de: "nein" },
  { it: "non", de: "nicht" },
  { it: "avanti", de: "vorwärts" },
  { it: "certo", de: "sicher" },
  { it: "davanti", de: "vorne" },
  { it: "dietro", de: "hinten" },
  { it: "dopo", de: "danach" },
  { it: "giù", de: "hinunter" },
  { it: "indietro", de: "zurück" },
  { it: "lì", de: "da" },
  { it: "meno", de: "weniger" },
  { it: "più", de: "mehr" },
  { it: "quasi", de: "fast" },
  { it: "spesso", de: "oft" },
  { it: "su", de: "hinauf" },
  { it: "qua", de: "hierher" },
  { it: "la destra", de: "die rechte Seite" },
  { it: "la sinistra", de: "die linke Seite" },
  { it: "tanto", de: "so viel" },
  { it: "troppo", de: "zu viel" },

  // Pronouns
  { it: "io", de: "ich" },
  { it: "tu", de: "du" },
  { it: "lui", de: "er" },
  { it: "lei", de: "sie" },
  { it: "noi", de: "wir" },
  { it: "voi", de: "ihr" },
  { it: "loro", de: "sie (Pl.)" },
  { it: "me", de: "mich" },
  { it: "te", de: "dich" },
  { it: "mi", de: "mir" },
  { it: "ti", de: "dir" },
  { it: "si", de: "sich" },
  { it: "ci", de: "uns" },
  { it: "nessuno", de: "niemand" },
  { it: "quale", de: "welcher" },

  // Discourse glue — the little words that join spoken sentences up
  { it: "allora", de: "also" },
  { it: "quindi", de: "deshalb" },
  { it: "però", de: "jedoch" },
  { it: "invece", de: "stattdessen" },
  { it: "anzi", de: "im Gegenteil" },
  { it: "almeno", de: "wenigstens" },
  { it: "soprattutto", de: "vor allem" },
  { it: "abbastanza", de: "ziemlich" },
  { it: "circa", de: "ungefähr" },
  { it: "insomma", de: "kurz gesagt" },
  { it: "comunque", de: "jedenfalls" },
  { it: "naturalmente", de: "natürlich" },
  { it: "volentieri", de: "gerne" },
  { it: "purtroppo", de: "leider" },
  { it: "davvero", de: "wirklich" },
  { it: "subito", de: "sofort" },
  { it: "insieme", de: "zusammen" },
  { it: "ancora", de: "noch" },
  { it: "già", de: "schon" },
  { it: "appena", de: "gerade eben" },
  { it: "forse", de: "vielleicht" },
  { it: "magari", de: "hoffentlich" },
];

// ---------------------------------------------------------------------------
// Sentence pool — short A1 Italian sentences with their German translation.
// These feed the "fill the blank" and "build the sentence" quiz exercises.
// `it` is the Italian sentence (tokens split on spaces), `de` its German
// meaning (shown as a hint), `blank` the single Italian token that gets removed
// for fill-in exercises, and `pos` its part of speech so that the multiple-
// choice distractors stay the same kind of word as the answer — noun, verb,
// adj, adv or num.
//
// Three questions of every quiz are drawn from here (fill by word bank, fill by
// typing, build the sentence), so the pool has to be big enough that a session
// doesn't keep serving the same handful. It is grouped by theme purely for
// upkeep; the game treats it as one flat list and draws at random (quiz.js
// keeps a short memory of what it just showed so the draws spread out).
//
// House rules when adding one — `tools/check-sentences.mjs` enforces them:
//   • 3–7 tokens. The build-the-sentence bank is tapped with a thumb.
//   • `blank` must be one whole token of `it`, appearing exactly once, and
//     never the first one (a capitalised option would give itself away).
//   • the German line must actually contain the blank's meaning — it is the
//     only clue the learner gets about which word is missing.
//   • words come from WORD_POOL (plus articles, prepositions and the inflected
//     forms of pool entries); no vocabulary is introduced here that the game
//     never teaches.
// ---------------------------------------------------------------------------
const SENTENCE_POOL = [
  // --- Essen & Trinken ---
  { it: "Io bevo il caffè", de: "Ich trinke den Kaffee", blank: "caffè", pos: "noun" },
  { it: "Tu mangi il pane", de: "Du isst das Brot", blank: "pane", pos: "noun" },
  { it: "Noi beviamo molta acqua", de: "Wir trinken viel Wasser", blank: "acqua", pos: "noun" },
  { it: "Io mangio una mela", de: "Ich esse einen Apfel", blank: "mela", pos: "noun" },
  { it: "Il vino è buono", de: "Der Wein ist gut", blank: "vino", pos: "noun" },
  { it: "Il fratello beve il tè", de: "Der Bruder trinkt den Tee", blank: "tè", pos: "noun" },
  { it: "La nonna fa il pane", de: "Die Großmutter macht das Brot", blank: "pane", pos: "noun" },
  { it: "Noi mangiamo il formaggio", de: "Wir essen den Käse", blank: "formaggio", pos: "noun" },
  { it: "La donna beve il vino", de: "Die Frau trinkt den Wein", blank: "vino", pos: "noun" },
  { it: "Noi mangiamo la frutta", de: "Wir essen das Obst", blank: "frutta", pos: "noun" },
  { it: "Il latte è freddo", de: "Die Milch ist kalt", blank: "latte", pos: "noun" },
  { it: "La pizza è calda", de: "Die Pizza ist heiß", blank: "pizza", pos: "noun" },
  { it: "Io voglio un gelato", de: "Ich will ein Eis", blank: "gelato", pos: "noun" },
  { it: "La pasta è buona", de: "Die Nudeln sind gut", blank: "pasta", pos: "noun" },
  { it: "Il pesce è caro", de: "Der Fisch ist teuer", blank: "caro", pos: "adj" },
  { it: "Io metto il sale nella pasta", de: "Ich tue das Salz in die Nudeln", blank: "sale", pos: "noun" },
  { it: "Io prendo lo zucchero", de: "Ich nehme den Zucker", blank: "zucchero", pos: "noun" },
  { it: "La colazione è alle otto", de: "Das Frühstück ist um acht", blank: "colazione", pos: "noun" },
  { it: "Il pranzo è a mezzogiorno", de: "Das Mittagessen ist am Mittag", blank: "pranzo", pos: "noun" },
  { it: "Noi ceniamo con gli amici", de: "Wir essen mit den Freunden zu Abend", blank: "ceniamo", pos: "verb" },
  { it: "Il cameriere porta il menù", de: "Der Kellner bringt die Speisekarte", blank: "cameriere", pos: "noun" },
  { it: "Io pago il conto", de: "Ich bezahle die Rechnung", blank: "conto", pos: "noun" },
  { it: "La bottiglia è vuota", de: "Die Flasche ist leer", blank: "vuota", pos: "adj" },
  { it: "Il bicchiere è pieno", de: "Das Glas ist voll", blank: "pieno", pos: "adj" },
  { it: "Tu cucini la carne", de: "Du kochst das Fleisch", blank: "cucini", pos: "verb" },
  { it: "Il pollo è nel piatto", de: "Das Hähnchen ist auf dem Teller", blank: "pollo", pos: "noun" },
  { it: "Io mangio un uovo", de: "Ich esse ein Ei", blank: "uovo", pos: "noun" },
  { it: "Lei prende un cappuccino", de: "Sie nimmt einen Cappuccino", blank: "cappuccino", pos: "noun" },
  { it: "Noi beviamo una birra", de: "Wir trinken ein Bier", blank: "birra", pos: "noun" },
  { it: "Il bambino ha fame", de: "Das Kind hat Hunger", blank: "bambino", pos: "noun" },
  { it: "Io ho sete", de: "Ich habe Durst", blank: "sete", pos: "noun" },
  { it: "La verdura è verde", de: "Das Gemüse ist grün", blank: "verdura", pos: "noun" },
  { it: "Tu prenoti un tavolo", de: "Du reservierst einen Tisch", blank: "prenoti", pos: "verb" },
  { it: "Il dolce arriva dopo", de: "Der Nachtisch kommt danach", blank: "dolce", pos: "noun" },
  { it: "Io uso la forchetta", de: "Ich benutze die Gabel", blank: "forchetta", pos: "noun" },
  { it: "Il coltello è sul tavolo", de: "Das Messer ist auf dem Tisch", blank: "coltello", pos: "noun" },
  { it: "Lui mangia gli spaghetti", de: "Er isst die Spaghetti", blank: "spaghetti", pos: "noun" },
  { it: "Il pomodoro è rosso", de: "Die Tomate ist rot", blank: "pomodoro", pos: "noun" },
  { it: "Io prendo un cucchiaio", de: "Ich nehme einen Löffel", blank: "cucchiaio", pos: "noun" },
  { it: "Il riso è bianco", de: "Der Reis ist weiß", blank: "riso", pos: "noun" },
  { it: "Noi compriamo il burro", de: "Wir kaufen die Butter", blank: "burro", pos: "noun" },
  { it: "Il pepe è nero", de: "Der Pfeffer ist schwarz", blank: "pepe", pos: "noun" },
  { it: "Lei cucina molto bene", de: "Sie kocht sehr gut", blank: "cucina", pos: "verb" },
  { it: "Io mangio poco", de: "Ich esse wenig", blank: "poco", pos: "adv" },

  // --- Familie & Menschen ---
  { it: "La madre legge un libro", de: "Die Mutter liest ein Buch", blank: "libro", pos: "noun" },
  { it: "Il padre lavora oggi", de: "Der Vater arbeitet heute", blank: "padre", pos: "noun" },
  { it: "La sorella ha un gatto", de: "Die Schwester hat eine Katze", blank: "gatto", pos: "noun" },
  { it: "Io ho un amico italiano", de: "Ich habe einen italienischen Freund", blank: "amico", pos: "noun" },
  { it: "La ragazza è felice", de: "Das Mädchen ist glücklich", blank: "felice", pos: "adj" },
  { it: "Il ragazzo corre veloce", de: "Der Junge läuft schnell", blank: "veloce", pos: "adj" },
  { it: "Mio fratello è alto", de: "Mein Bruder ist groß", blank: "alto", pos: "adj" },
  { it: "Mia sorella è giovane", de: "Meine Schwester ist jung", blank: "giovane", pos: "adj" },
  { it: "Il nonno legge il giornale", de: "Der Großvater liest die Zeitung", blank: "giornale", pos: "noun" },
  { it: "La nonna abita in campagna", de: "Die Großmutter wohnt auf dem Land", blank: "abita", pos: "verb" },
  { it: "La famiglia mangia insieme", de: "Die Familie isst zusammen", blank: "insieme", pos: "adv" },
  { it: "Il figlio dorme in camera", de: "Der Sohn schläft im Zimmer", blank: "figlio", pos: "noun" },
  { it: "La figlia studia italiano", de: "Die Tochter lernt Italienisch", blank: "studia", pos: "verb" },
  { it: "Mio marito cucina bene", de: "Mein Ehemann kocht gut", blank: "bene", pos: "adv" },
  { it: "Mia moglie canta sempre", de: "Meine Ehefrau singt immer", blank: "sempre", pos: "adv" },
  { it: "Il bambino gioca in giardino", de: "Das Kind spielt im Garten", blank: "gioca", pos: "verb" },
  { it: "La donna chiama il figlio", de: "Die Frau ruft den Sohn", blank: "chiama", pos: "verb" },
  { it: "Il mio amico è simpatico", de: "Mein Freund ist sympathisch", blank: "simpatico", pos: "adj" },
  { it: "La signora è gentile", de: "Die Dame ist freundlich", blank: "gentile", pos: "adj" },
  { it: "Il papà torna a casa", de: "Der Papa kommt nach Hause zurück", blank: "torna", pos: "verb" },
  { it: "La mamma fa la cena", de: "Die Mama macht das Abendessen", blank: "cena", pos: "noun" },
  { it: "Io amo la mia famiglia", de: "Ich liebe meine Familie", blank: "famiglia", pos: "noun" },
  { it: "Il compagno arriva domani", de: "Der Partner kommt morgen an", blank: "domani", pos: "adv" },
  { it: "I bambini sono piccoli", de: "Die Kinder sind klein", blank: "piccoli", pos: "adj" },
  { it: "Il nonno è vecchio", de: "Der Großvater ist alt", blank: "vecchio", pos: "adj" },
  { it: "La ragazza è bionda", de: "Das Mädchen ist blond", blank: "bionda", pos: "adj" },
  { it: "Lui aspetta la moglie", de: "Er wartet auf die Ehefrau", blank: "aspetta", pos: "verb" },
  { it: "Il bambino è bravo", de: "Das Kind ist tüchtig", blank: "bravo", pos: "adj" },
  { it: "Noi conosciamo la signora", de: "Wir kennen die Dame", blank: "conosciamo", pos: "verb" },
  { it: "Il nome è italiano", de: "Der Name ist italienisch", blank: "nome", pos: "noun" },
  { it: "Lei scrive il cognome", de: "Sie schreibt den Nachnamen", blank: "cognome", pos: "noun" },
  { it: "La gente parla molto", de: "Die Leute reden viel", blank: "gente", pos: "noun" },

  // --- Haus & Wohnen ---
  { it: "La casa è bianca", de: "Das Haus ist weiß", blank: "casa", pos: "noun" },
  { it: "La casa ha una porta", de: "Das Haus hat eine Tür", blank: "porta", pos: "noun" },
  { it: "La finestra è grande", de: "Das Fenster ist groß", blank: "finestra", pos: "noun" },
  { it: "Il letto è nuovo", de: "Das Bett ist neu", blank: "letto", pos: "noun" },
  { it: "La sedia è piccola", de: "Der Stuhl ist klein", blank: "piccola", pos: "adj" },
  { it: "Il libro è sul tavolo", de: "Das Buch ist auf dem Tisch", blank: "tavolo", pos: "noun" },
  { it: "La cucina è pulita", de: "Die Küche ist sauber", blank: "pulita", pos: "adj" },
  { it: "Il bagno è piccolo", de: "Das Badezimmer ist klein", blank: "bagno", pos: "noun" },
  { it: "La camera è grande", de: "Das Zimmer ist groß", blank: "camera", pos: "noun" },
  { it: "Io cerco la chiave", de: "Ich suche den Schlüssel", blank: "chiave", pos: "noun" },
  { it: "La lampada è vecchia", de: "Die Lampe ist alt", blank: "lampada", pos: "noun" },
  { it: "Lo specchio è in bagno", de: "Der Spiegel ist im Badezimmer", blank: "specchio", pos: "noun" },
  { it: "Il telefono è sul letto", de: "Das Telefon ist auf dem Bett", blank: "telefono", pos: "noun" },
  { it: "Io guardo l'orologio", de: "Ich schaue auf die Uhr", blank: "guardo", pos: "verb" },
  { it: "L'appartamento è nuovo", de: "Die Wohnung ist neu", blank: "nuovo", pos: "adj" },
  { it: "Noi puliamo la cucina", de: "Wir putzen die Küche", blank: "puliamo", pos: "verb" },
  { it: "Il giardino è verde", de: "Der Garten ist grün", blank: "giardino", pos: "noun" },
  { it: "La doccia è calda", de: "Die Dusche ist heiß", blank: "doccia", pos: "noun" },
  { it: "Il quadro è bello", de: "Das Bild ist schön", blank: "quadro", pos: "noun" },
  { it: "La pianta è alla finestra", de: "Die Pflanze ist am Fenster", blank: "pianta", pos: "noun" },
  { it: "Io apro la porta", de: "Ich öffne die Tür", blank: "apro", pos: "verb" },
  { it: "Tu chiudi la finestra", de: "Du schließt das Fenster", blank: "chiudi", pos: "verb" },
  { it: "Il soggiorno è pieno", de: "Das Wohnzimmer ist voll", blank: "soggiorno", pos: "noun" },
  { it: "Io abito in città", de: "Ich wohne in der Stadt", blank: "abito", pos: "verb" },
  { it: "La chiave è nella borsa", de: "Der Schlüssel ist in der Tasche", blank: "borsa", pos: "noun" },
  { it: "Il piano è vuoto", de: "Die Etage ist leer", blank: "vuoto", pos: "adj" },

  // --- Tiere ---
  { it: "Il cane è grande", de: "Der Hund ist groß", blank: "cane", pos: "noun" },
  { it: "Il gatto dorme molto", de: "Die Katze schläft viel", blank: "gatto", pos: "noun" },
  { it: "Il cavallo corre veloce", de: "Das Pferd rennt schnell", blank: "cavallo", pos: "noun" },
  { it: "L'uccello canta la mattina", de: "Der Vogel singt am Morgen", blank: "canta", pos: "verb" },
  { it: "La mucca beve acqua", de: "Die Kuh trinkt Wasser", blank: "mucca", pos: "noun" },
  { it: "Il topo è piccolo", de: "Die Maus ist klein", blank: "topo", pos: "noun" },
  { it: "Il maiale è sporco", de: "Das Schwein ist schmutzig", blank: "sporco", pos: "adj" },
  { it: "La pecora è bianca", de: "Das Schaf ist weiß", blank: "pecora", pos: "noun" },
  { it: "Il pesce è nel mare", de: "Der Fisch ist im Meer", blank: "pesce", pos: "noun" },
  { it: "Il cane mangia la carne", de: "Der Hund isst das Fleisch", blank: "mangia", pos: "verb" },
  { it: "Il gatto beve il latte", de: "Die Katze trinkt die Milch", blank: "beve", pos: "verb" },
  { it: "L'animale ha fame", de: "Das Tier hat Hunger", blank: "fame", pos: "noun" },
  { it: "Il cane dorme in giardino", de: "Der Hund schläft im Garten", blank: "dorme", pos: "verb" },
  { it: "Noi guardiamo gli uccelli", de: "Wir schauen die Vögel an", blank: "guardiamo", pos: "verb" },

  // --- Stadt & Wege ---
  { it: "La città è grande", de: "Die Stadt ist groß", blank: "città", pos: "noun" },
  { it: "La strada è lunga", de: "Die Straße ist lang", blank: "lunga", pos: "adj" },
  { it: "Io vado al negozio", de: "Ich gehe zum Geschäft", blank: "vado", pos: "verb" },
  { it: "Il ristorante è in piazza", de: "Das Restaurant ist am Platz", blank: "ristorante", pos: "noun" },
  { it: "La scuola è lontana", de: "Die Schule ist weit weg", blank: "lontana", pos: "adj" },
  { it: "La stazione è vicina", de: "Der Bahnhof ist nah", blank: "vicina", pos: "adj" },
  { it: "Il treno arriva alla stazione", de: "Der Zug kommt am Bahnhof an", blank: "stazione", pos: "noun" },
  { it: "I bambini giocano nel parco", de: "Die Kinder spielen im Park", blank: "parco", pos: "noun" },
  { it: "La chiesa è molto vecchia", de: "Die Kirche ist sehr alt", blank: "vecchia", pos: "adj" },
  { it: "Noi andiamo al mercato", de: "Wir gehen zum Markt", blank: "mercato", pos: "noun" },
  { it: "L'ufficio apre alle nove", de: "Das Büro öffnet um neun", blank: "apre", pos: "verb" },
  { it: "Noi visitiamo il museo", de: "Wir besuchen das Museum", blank: "museo", pos: "noun" },
  { it: "La piazza è piena", de: "Der Platz ist voll", blank: "piena", pos: "adj" },
  { it: "Noi cerchiamo un albergo", de: "Wir suchen ein Hotel", blank: "cerchiamo", pos: "verb" },
  { it: "Il bar è sempre pieno", de: "Die Bar ist immer voll", blank: "sempre", pos: "adv" },
  { it: "Il film comincia alle otto", de: "Der Film beginnt um acht", blank: "comincia", pos: "verb" },
  { it: "Il teatro è in centro", de: "Das Theater ist im Zentrum", blank: "centro", pos: "noun" },
  { it: "Il supermercato è grande", de: "Der Supermarkt ist groß", blank: "supermercato", pos: "noun" },
  { it: "Io cerco la farmacia", de: "Ich suche die Apotheke", blank: "farmacia", pos: "noun" },
  { it: "La posta è dietro la chiesa", de: "Die Post ist hinter der Kirche", blank: "dietro", pos: "adv" },
  { it: "La fermata è qui", de: "Die Haltestelle ist hier", blank: "qui", pos: "adv" },
  { it: "La polizia arriva subito", de: "Die Polizei kommt sofort", blank: "subito", pos: "adv" },
  { it: "L'università è in città", de: "Die Universität ist in der Stadt", blank: "città", pos: "noun" },
  { it: "Il parco è davanti alla casa", de: "Der Park ist vor dem Haus", blank: "davanti", pos: "adv" },
  { it: "La banca chiude presto", de: "Die Bank schließt früh", blank: "chiude", pos: "verb" },
  { it: "Il paese è piccolo", de: "Das Land ist klein", blank: "paese", pos: "noun" },
  { it: "Il cinema è vicino", de: "Das Kino ist nah", blank: "cinema", pos: "noun" },
  { it: "Noi mangiamo in pizzeria", de: "Wir essen in der Pizzeria", blank: "pizzeria", pos: "noun" },

  // --- Reisen & Verkehr ---
  { it: "La macchina è rossa", de: "Das Auto ist rot", blank: "macchina", pos: "noun" },
  { it: "Il treno parte adesso", de: "Der Zug fährt jetzt ab", blank: "parte", pos: "verb" },
  { it: "L'autobus arriva tardi", de: "Der Bus kommt spät an", blank: "tardi", pos: "adv" },
  { it: "La bicicletta è vecchia", de: "Das Fahrrad ist alt", blank: "bicicletta", pos: "noun" },
  { it: "L'aereo parte alle sei", de: "Das Flugzeug fliegt um sechs ab", blank: "sei", pos: "num" },
  { it: "La nave è grande", de: "Das Schiff ist groß", blank: "nave", pos: "noun" },
  { it: "Il viaggio è lungo", de: "Die Reise ist lang", blank: "viaggio", pos: "noun" },
  { it: "La vacanza comincia domani", de: "Der Urlaub beginnt morgen", blank: "vacanza", pos: "noun" },
  { it: "Io compro il biglietto", de: "Ich kaufe die Fahrkarte", blank: "biglietto", pos: "noun" },
  { it: "Il passaporto è nella borsa", de: "Der Reisepass ist in der Tasche", blank: "passaporto", pos: "noun" },
  { it: "Io porto la valigia", de: "Ich trage den Koffer", blank: "porto", pos: "verb" },
  { it: "Il bambino porta lo zaino", de: "Das Kind trägt den Rucksack", blank: "zaino", pos: "noun" },
  { it: "Noi viaggiamo in treno", de: "Wir reisen mit dem Zug", blank: "viaggiamo", pos: "verb" },
  { it: "Il taxi aspetta fuori", de: "Das Taxi wartet draußen", blank: "fuori", pos: "adv" },
  { it: "Io prendo l'autobus", de: "Ich nehme den Bus", blank: "prendo", pos: "verb" },
  { it: "La moto è veloce", de: "Das Motorrad ist schnell", blank: "moto", pos: "noun" },
  { it: "Il parcheggio è pieno", de: "Der Parkplatz ist voll", blank: "parcheggio", pos: "noun" },
  { it: "Noi partiamo lunedì", de: "Wir fahren am Montag ab", blank: "partiamo", pos: "verb" },
  { it: "Io viaggio spesso", de: "Ich reise oft", blank: "spesso", pos: "adv" },
  { it: "Il documento è nello zaino", de: "Das Dokument ist im Rucksack", blank: "documento", pos: "noun" },
  { it: "Noi andiamo all'estero", de: "Wir gehen ins Ausland", blank: "andiamo", pos: "verb" },
  { it: "La strada è stretta", de: "Die Straße ist eng", blank: "stretta", pos: "adj" },

  // --- Arbeit, Schule & Sprache ---
  { it: "Il libro è nuovo", de: "Das Buch ist neu", blank: "libro", pos: "noun" },
  { it: "Io studio italiano", de: "Ich lerne Italienisch", blank: "studio", pos: "verb" },
  { it: "La lezione è difficile", de: "Die Lektion ist schwierig", blank: "difficile", pos: "adj" },
  { it: "L'esercizio è facile", de: "Die Übung ist einfach", blank: "facile", pos: "adj" },
  { it: "Il professore parla italiano", de: "Der Lehrer spricht Italienisch", blank: "professore", pos: "noun" },
  { it: "Lo studente scrive una lettera", de: "Der Student schreibt einen Brief", blank: "scrive", pos: "verb" },
  { it: "Io leggo il giornale", de: "Ich lese die Zeitung", blank: "leggo", pos: "verb" },
  { it: "La scuola comincia a settembre", de: "Die Schule beginnt im September", blank: "settembre", pos: "noun" },
  { it: "Il lavoro è importante", de: "Die Arbeit ist wichtig", blank: "importante", pos: "adj" },
  { it: "Io lavoro in ufficio", de: "Ich arbeite im Büro", blank: "ufficio", pos: "noun" },
  { it: "Noi impariamo le parole", de: "Wir lernen die Wörter", blank: "impariamo", pos: "verb" },
  { it: "Tu scrivi con la penna", de: "Du schreibst mit dem Stift", blank: "penna", pos: "noun" },
  { it: "Il quaderno è sul tavolo", de: "Das Heft ist auf dem Tisch", blank: "quaderno", pos: "noun" },
  { it: "La matita è rossa", de: "Der Bleistift ist rot", blank: "matita", pos: "noun" },
  { it: "Il corso finisce a giugno", de: "Der Kurs endet im Juni", blank: "finisce", pos: "verb" },
  { it: "La domanda è difficile", de: "Die Frage ist schwierig", blank: "domanda", pos: "noun" },
  { it: "La risposta è facile", de: "Die Antwort ist einfach", blank: "risposta", pos: "noun" },
  { it: "Il problema è grande", de: "Das Problem ist groß", blank: "problema", pos: "noun" },
  { it: "Io ho una buona idea", de: "Ich habe eine gute Idee", blank: "idea", pos: "noun" },
  { it: "Il dottore lavora in ospedale", de: "Der Arzt arbeitet im Krankenhaus", blank: "dottore", pos: "noun" },
  { it: "Il cameriere lavora la sera", de: "Der Kellner arbeitet am Abend", blank: "lavora", pos: "verb" },
  { it: "Io insegno italiano", de: "Ich unterrichte Italienisch", blank: "insegno", pos: "verb" },
  { it: "Noi ripetiamo la lezione", de: "Wir wiederholen die Lektion", blank: "ripetiamo", pos: "verb" },
  { it: "Lui capisce la domanda", de: "Er versteht die Frage", blank: "capisce", pos: "verb" },
  { it: "La classe è piena", de: "Die Klasse ist voll", blank: "classe", pos: "noun" },
  { it: "Io parlo poco italiano", de: "Ich spreche wenig Italienisch", blank: "parlo", pos: "verb" },
  { it: "Tu non capisci la parola", de: "Du verstehst das Wort nicht", blank: "parola", pos: "noun" },
  { it: "Lui scrive una e-mail", de: "Er schreibt eine E-Mail", blank: "e-mail", pos: "noun" },
  { it: "Io telefono a mia madre", de: "Ich rufe meine Mutter an", blank: "telefono", pos: "verb" },
  { it: "Noi rispondiamo alla domanda", de: "Wir antworten auf die Frage", blank: "rispondiamo", pos: "verb" },
  { it: "La lingua italiana è bella", de: "Die italienische Sprache ist schön", blank: "lingua", pos: "noun" },
  { it: "Tu ripeti la parola", de: "Du wiederholst das Wort", blank: "ripeti", pos: "verb" },
  { it: "La lettera è per il nonno", de: "Der Brief ist für den Großvater", blank: "lettera", pos: "noun" },
  { it: "Io spedisco una cartolina", de: "Ich verschicke eine Postkarte", blank: "spedisco", pos: "verb" },
  { it: "Il francobollo è sulla busta", de: "Die Briefmarke ist auf dem Umschlag", blank: "francobollo", pos: "noun" },
  { it: "Io chiedo un favore", de: "Ich bitte um einen Gefallen", blank: "favore", pos: "noun" },
  { it: "Il computer è nuovo", de: "Der Computer ist neu", blank: "computer", pos: "noun" },
  { it: "Il cellulare non funziona", de: "Das Handy funktioniert nicht", blank: "funziona", pos: "verb" },

  // --- Zeit & Alltag ---
  { it: "Oggi fa freddo", de: "Heute ist es kalt", blank: "freddo", pos: "adj" },
  { it: "Domani vado al mare", de: "Morgen gehe ich ans Meer", blank: "mare", pos: "noun" },
  { it: "Io mi sveglio presto", de: "Ich wache früh auf", blank: "presto", pos: "adv" },
  { it: "La mattina bevo il caffè", de: "Am Morgen trinke ich den Kaffee", blank: "bevo", pos: "verb" },
  { it: "La sera guardo la tv", de: "Am Abend schaue ich fern", blank: "guardo", pos: "verb" },
  { it: "La notte dormo bene", de: "Nachts schlafe ich gut", blank: "bene", pos: "adv" },
  { it: "Il giorno è lungo", de: "Der Tag ist lang", blank: "giorno", pos: "noun" },
  { it: "La settimana comincia lunedì", de: "Die Woche beginnt am Montag", blank: "lunedì", pos: "noun" },
  { it: "Il mese di agosto è caldo", de: "Der Monat August ist heiß", blank: "caldo", pos: "adj" },
  { it: "L'anno finisce a dicembre", de: "Das Jahr endet im Dezember", blank: "dicembre", pos: "noun" },
  { it: "Adesso io ho tempo", de: "Jetzt habe ich Zeit", blank: "tempo", pos: "noun" },
  { it: "Io arrivo sempre tardi", de: "Ich komme immer spät an", blank: "tardi", pos: "adv" },
  { it: "Lui parte domenica", de: "Er fährt am Sonntag ab", blank: "domenica", pos: "noun" },
  { it: "Sabato andiamo al cinema", de: "Am Samstag gehen wir ins Kino", blank: "cinema", pos: "noun" },
  { it: "Il compleanno è a maggio", de: "Der Geburtstag ist im Mai", blank: "compleanno", pos: "noun" },
  { it: "L'appuntamento è alle tre", de: "Der Termin ist um drei", blank: "tre", pos: "num" },
  { it: "Io aspetto un momento", de: "Ich warte einen Moment", blank: "momento", pos: "noun" },
  { it: "Noi usciamo la sera", de: "Wir gehen am Abend aus", blank: "usciamo", pos: "verb" },
  { it: "Tu dormi troppo", de: "Du schläfst zu viel", blank: "troppo", pos: "adv" },
  { it: "Io non ho fretta", de: "Ich habe keine Eile", blank: "fretta", pos: "noun" },
  { it: "Il treno arriva alle quattro", de: "Der Zug kommt um vier an", blank: "quattro", pos: "num" },
  { it: "Lei lavora anche martedì", de: "Sie arbeitet auch am Dienstag", blank: "martedì", pos: "noun" },
  { it: "Io torno a mezzanotte", de: "Ich komme um Mitternacht zurück", blank: "mezzanotte", pos: "noun" },
  { it: "Il pomeriggio è lungo", de: "Der Nachmittag ist lang", blank: "pomeriggio", pos: "noun" },
  { it: "Noi mangiamo alle sette", de: "Wir essen um sieben", blank: "sette", pos: "num" },
  { it: "Lui aspetta da un'ora", de: "Er wartet seit einer Stunde", blank: "aspetta", pos: "verb" },

  // --- Wetter & Natur ---
  { it: "La neve è bianca", de: "Der Schnee ist weiß", blank: "bianca", pos: "adj" },
  { it: "Il mare è grande", de: "Das Meer ist groß", blank: "grande", pos: "adj" },
  { it: "Il sole è caldo", de: "Die Sonne ist heiß", blank: "sole", pos: "noun" },
  { it: "La luna è bella", de: "Der Mond ist schön", blank: "bella", pos: "adj" },
  { it: "Le stelle sono nel cielo", de: "Die Sterne sind am Himmel", blank: "cielo", pos: "noun" },
  { it: "La montagna è alta", de: "Der Berg ist hoch", blank: "alta", pos: "adj" },
  { it: "Il fiume è lungo", de: "Der Fluss ist lang", blank: "fiume", pos: "noun" },
  { it: "L'albero è verde", de: "Der Baum ist grün", blank: "verde", pos: "adj" },
  { it: "Il fiore è giallo", de: "Die Blume ist gelb", blank: "fiore", pos: "noun" },
  { it: "La pioggia arriva presto", de: "Der Regen kommt früh", blank: "pioggia", pos: "noun" },
  { it: "Il vento è forte", de: "Der Wind ist stark", blank: "forte", pos: "adj" },
  { it: "Il fuoco è caldo", de: "Das Feuer ist heiß", blank: "fuoco", pos: "noun" },
  { it: "Noi camminiamo nel bosco", de: "Wir laufen im Wald", blank: "camminiamo", pos: "verb" },
  { it: "La spiaggia è piena", de: "Der Strand ist voll", blank: "spiaggia", pos: "noun" },
  { it: "Oggi piove molto", de: "Heute regnet es viel", blank: "molto", pos: "adv" },
  { it: "In estate fa caldo", de: "Im Sommer ist es heiß", blank: "estate", pos: "noun" },
  { it: "In inverno fa freddo", de: "Im Winter ist es kalt", blank: "inverno", pos: "noun" },
  { it: "La primavera è bella", de: "Der Frühling ist schön", blank: "primavera", pos: "noun" },
  { it: "Il lago è freddo", de: "Der See ist kalt", blank: "lago", pos: "noun" },
  { it: "La terra è nera", de: "Die Erde ist schwarz", blank: "terra", pos: "noun" },

  // --- Kleidung & Farben ---
  { it: "La mela è rossa", de: "Der Apfel ist rot", blank: "mela", pos: "noun" },
  { it: "La giacca è nera", de: "Die Jacke ist schwarz", blank: "nera", pos: "adj" },
  { it: "Le scarpe sono nuove", de: "Die Schuhe sind neu", blank: "nuove", pos: "adj" },
  { it: "Il cappello è marrone", de: "Der Hut ist braun", blank: "marrone", pos: "adj" },
  { it: "I pantaloni sono lunghi", de: "Die Hose ist lang", blank: "pantaloni", pos: "noun" },
  { it: "La camicia è bianca", de: "Das Hemd ist weiß", blank: "camicia", pos: "noun" },
  { it: "La gonna è corta", de: "Der Rock ist kurz", blank: "corta", pos: "adj" },
  { it: "Il maglione è caldo", de: "Der Pullover ist warm", blank: "maglione", pos: "noun" },
  { it: "Il cappotto è grigio", de: "Der Mantel ist grau", blank: "grigio", pos: "adj" },
  { it: "La maglietta è gialla", de: "Das T-Shirt ist gelb", blank: "maglietta", pos: "noun" },
  { it: "Io compro un vestito", de: "Ich kaufe ein Kleid", blank: "vestito", pos: "noun" },
  { it: "La borsa è piccola", de: "Die Tasche ist klein", blank: "borsa", pos: "noun" },
  { it: "Le calze sono blu", de: "Die Socken sind blau", blank: "blu", pos: "adj" },
  { it: "Il colore è bello", de: "Die Farbe ist schön", blank: "colore", pos: "noun" },
  { it: "Gli occhiali sono nuovi", de: "Die Brille ist neu", blank: "occhiali", pos: "noun" },
  { it: "L'ombrello è rosso", de: "Der Schirm ist rot", blank: "rosso", pos: "adj" },
  { it: "La scarpa è sporca", de: "Der Schuh ist schmutzig", blank: "scarpa", pos: "noun" },

  // --- Körper & Gesundheit ---
  { it: "La testa mi fa male", de: "Der Kopf tut mir weh", blank: "testa", pos: "noun" },
  { it: "La mano è fredda", de: "Die Hand ist kalt", blank: "mano", pos: "noun" },
  { it: "Lei ha gli occhi verdi", de: "Sie hat grüne Augen", blank: "verdi", pos: "adj" },
  { it: "La bocca è piccola", de: "Der Mund ist klein", blank: "bocca", pos: "noun" },
  { it: "Il naso è lungo", de: "Die Nase ist lang", blank: "naso", pos: "noun" },
  { it: "Il braccio è forte", de: "Der Arm ist stark", blank: "braccio", pos: "noun" },
  { it: "La gamba è lunga", de: "Das Bein ist lang", blank: "gamba", pos: "noun" },
  { it: "Il cuore è debole", de: "Das Herz ist schwach", blank: "debole", pos: "adj" },
  { it: "I capelli sono biondi", de: "Die Haare sind blond", blank: "capelli", pos: "noun" },
  { it: "Il dente è bianco", de: "Der Zahn ist weiß", blank: "dente", pos: "noun" },
  { it: "Il bambino è malato", de: "Das Kind ist krank", blank: "malato", pos: "adj" },
  { it: "Lui è molto stanco", de: "Er ist sehr müde", blank: "stanco", pos: "adj" },
  { it: "Io prendo la medicina", de: "Ich nehme die Medizin", blank: "medicina", pos: "noun" },
  { it: "Io ho bisogno di aiuto", de: "Ich brauche Hilfe", blank: "bisogno", pos: "noun" },
  { it: "Il piede è sporco", de: "Der Fuß ist schmutzig", blank: "piede", pos: "noun" },
  { it: "La faccia è pulita", de: "Das Gesicht ist sauber", blank: "faccia", pos: "noun" },

  // --- Freizeit, Geld & Gefühle ---
  { it: "Io ascolto la musica", de: "Ich höre die Musik", blank: "musica", pos: "noun" },
  { it: "Noi guardiamo un film", de: "Wir schauen einen Film", blank: "film", pos: "noun" },
  { it: "Lei canta una canzone", de: "Sie singt ein Lied", blank: "canzone", pos: "noun" },
  { it: "I bambini ballano insieme", de: "Die Kinder tanzen zusammen", blank: "ballano", pos: "verb" },
  { it: "I ragazzi giocano insieme", de: "Die Jungen spielen zusammen", blank: "giocano", pos: "verb" },
  { it: "La festa comincia adesso", de: "Die Party beginnt jetzt", blank: "adesso", pos: "adv" },
  { it: "Il regalo è per te", de: "Das Geschenk ist für dich", blank: "regalo", pos: "noun" },
  { it: "Il ragazzo è triste", de: "Der Junge ist traurig", blank: "triste", pos: "adj" },
  { it: "Io ho paura", de: "Ich habe Angst", blank: "paura", pos: "noun" },
  { it: "Lo sport è importante", de: "Der Sport ist wichtig", blank: "sport", pos: "noun" },
  { it: "Io leggo un libro interessante", de: "Ich lese ein interessantes Buch", blank: "interessante", pos: "adj" },
  { it: "La storia è bella", de: "Die Geschichte ist schön", blank: "storia", pos: "noun" },
  { it: "Noi andiamo alla festa", de: "Wir gehen zur Party", blank: "festa", pos: "noun" },
  { it: "Lei balla molto bene", de: "Sie tanzt sehr gut", blank: "balla", pos: "verb" },
  { it: "Io preferisco il mare", de: "Ich bevorzuge das Meer", blank: "preferisco", pos: "verb" },
  { it: "Il prezzo è alto", de: "Der Preis ist hoch", blank: "prezzo", pos: "noun" },
  { it: "Io non ho soldi", de: "Ich habe kein Geld", blank: "soldi", pos: "noun" },
  { it: "La spesa è cara", de: "Der Einkauf ist teuer", blank: "cara", pos: "adj" },
  { it: "Il negozio apre alle nove", de: "Das Geschäft öffnet um neun", blank: "nove", pos: "num" },
  { it: "Io compro il pane", de: "Ich kaufe das Brot", blank: "compro", pos: "verb" },
  { it: "Lui paga con la carta", de: "Er bezahlt mit der Karte", blank: "paga", pos: "verb" },
  { it: "Il libro costa dieci euro", de: "Das Buch kostet zehn Euro", blank: "dieci", pos: "num" },
  { it: "Noi cerchiamo un regalo", de: "Wir suchen ein Geschenk", blank: "cerchiamo", pos: "verb" },
  { it: "Il mercato è in piazza", de: "Der Markt ist am Platz", blank: "piazza", pos: "noun" },
  { it: "La vita è bella", de: "Das Leben ist schön", blank: "vita", pos: "noun" },
  { it: "L'amore è forte", de: "Die Liebe ist stark", blank: "forte", pos: "adj" },

  // --- Alltagsverben ---
  { it: "La donna legge il libro", de: "Die Frau liest das Buch", blank: "legge", pos: "verb" },
  { it: "Noi beviamo il latte", de: "Wir trinken die Milch", blank: "beviamo", pos: "verb" },
  { it: "Il bambino dorme molto", de: "Das Kind schläft viel", blank: "dorme", pos: "verb" },
  { it: "Io aiuto mia madre", de: "Ich helfe meiner Mutter", blank: "aiuto", pos: "verb" },
  { it: "Tu credi a tutto", de: "Du glaubst alles", blank: "credi", pos: "verb" },
  { it: "Lui pensa a lei", de: "Er denkt an sie", blank: "pensa", pos: "verb" },
  { it: "Noi speriamo di vincere", de: "Wir hoffen zu gewinnen", blank: "speriamo", pos: "verb" },
  { it: "Io ricordo il nome", de: "Ich erinnere mich an den Namen", blank: "ricordo", pos: "verb" },
  { it: "Tu dimentichi le chiavi", de: "Du vergisst die Schlüssel", blank: "dimentichi", pos: "verb" },
  { it: "Lei prova un vestito", de: "Sie probiert ein Kleid", blank: "prova", pos: "verb" },
  { it: "Noi usiamo il computer", de: "Wir benutzen den Computer", blank: "usiamo", pos: "verb" },
  { it: "Io lascio la borsa qui", de: "Ich lasse die Tasche hier", blank: "lascio", pos: "verb" },
  { it: "Lui tiene il bambino", de: "Er hält das Kind", blank: "tiene", pos: "verb" },
  { it: "Io perdo sempre le chiavi", de: "Ich verliere immer die Schlüssel", blank: "perdo", pos: "verb" },
  { it: "Noi vinciamo sempre", de: "Wir gewinnen immer", blank: "vinciamo", pos: "verb" },
  { it: "Tu trovi il libro", de: "Du findest das Buch", blank: "trovi", pos: "verb" },
  { it: "Io do il pane al cane", de: "Ich gebe dem Hund das Brot", blank: "do", pos: "verb" },
  { it: "Lei mette il libro qui", de: "Sie legt das Buch hierhin", blank: "mette", pos: "verb" },
  { it: "Noi entriamo in casa", de: "Wir treten ins Haus ein", blank: "entriamo", pos: "verb" },
  { it: "Lui esce con gli amici", de: "Er geht mit den Freunden aus", blank: "esce", pos: "verb" },
  { it: "Io vengo domani", de: "Ich komme morgen", blank: "vengo", pos: "verb" },
  { it: "Tu vai a scuola", de: "Du gehst zur Schule", blank: "vai", pos: "verb" },
  { it: "Noi stiamo bene", de: "Uns geht es gut", blank: "stiamo", pos: "verb" },
  { it: "Lei dice di sì", de: "Sie sagt ja", blank: "dice", pos: "verb" },
  { it: "Io vedo il mare", de: "Ich sehe das Meer", blank: "vedo", pos: "verb" },
  { it: "Tu senti la musica", de: "Du hörst die Musik", blank: "senti", pos: "verb" },
  { it: "Noi sappiamo la risposta", de: "Wir wissen die Antwort", blank: "sappiamo", pos: "verb" },
  { it: "Lui vuole un caffè", de: "Er will einen Kaffee", blank: "vuole", pos: "verb" },
  { it: "Io posso aiutare", de: "Ich kann helfen", blank: "posso", pos: "verb" },
  { it: "Tu devi studiare", de: "Du musst lernen", blank: "devi", pos: "verb" },
  { it: "Noi viviamo in città", de: "Wir leben in der Stadt", blank: "viviamo", pos: "verb" },
  { it: "Lei ama i gatti", de: "Sie liebt die Katzen", blank: "ama", pos: "verb" },
  { it: "Io incontro un amico", de: "Ich treffe einen Freund", blank: "incontro", pos: "verb" },
  { it: "Tu cambi lavoro", de: "Du wechselst die Arbeit", blank: "cambi", pos: "verb" },
  { it: "Lui fuma troppo", de: "Er raucht zu viel", blank: "fuma", pos: "verb" },
  { it: "Noi restiamo a casa", de: "Wir bleiben zu Hause", blank: "restiamo", pos: "verb" },
  { it: "Io riesco a capire", de: "Ich schaffe es zu verstehen", blank: "riesco", pos: "verb" },
  { it: "Lei diventa vecchia", de: "Sie wird alt", blank: "diventa", pos: "verb" },
  { it: "Il gatto sembra stanco", de: "Die Katze scheint müde", blank: "sembra", pos: "verb" },
  { it: "Io domando il prezzo", de: "Ich frage nach dem Preis", blank: "domando", pos: "verb" },
];

// ---------------------------------------------------------------------------
// The bar — what is said at the Tresen (see tavern.js). The keeper asks, the
// hero orders, and the missing word IS the order: whatever fills the gap is what
// lands on the counter, so `blank` and `item` are the same word seen twice, once
// as language and once as a thing to eat.
//
// The same house rules as SENTENCE_POOL apply and `tools/check-sentences.mjs`
// checks this pool against them too — no punctuation inside a line (tokens split
// on spaces), the blank one whole token and never the first, and no vocabulary
// the game doesn't teach. What differs is that there is no `pos`: the distractors
// are the OTHER things on the menu, which is what a menu is, so every blank here
// has to be one of BAR_ITEMS. Two lines per item, so the same order doesn't come
// round twice in a session.
//
// Every item needs art in tavern.js (TAV_MEAL) — adding a line for something the
// keeper cannot actually put on the counter is the one way to break this pool.
// ---------------------------------------------------------------------------
const BAR_ITEMS = ["pane", "formaggio", "mela", "pollo", "vino", "birra", "latte"];

const BAR_ORDER_POOL = [
  { it: "Voglio il pane per favore", de: "Ich will das Brot, bitte", blank: "pane" },
  { it: "Prendo un pane caldo per favore", de: "Ich nehme ein warmes Brot, bitte", blank: "pane" },
  { it: "Prendo del formaggio per favore", de: "Ich nehme etwas Käse, bitte", blank: "formaggio" },
  { it: "Voglio il formaggio per favore", de: "Ich will den Käse, bitte", blank: "formaggio" },
  { it: "Voglio una mela per favore", de: "Ich will einen Apfel, bitte", blank: "mela" },
  { it: "Prendo una mela rossa per favore", de: "Ich nehme einen roten Apfel, bitte", blank: "mela" },
  { it: "Prendo il pollo per favore", de: "Ich nehme das Hähnchen, bitte", blank: "pollo" },
  { it: "Voglio il pollo caldo per favore", de: "Ich will das warme Hähnchen, bitte", blank: "pollo" },
  { it: "Voglio un bicchiere di vino", de: "Ich will ein Glas Wein", blank: "vino" },
  { it: "Prendo il vino rosso per favore", de: "Ich nehme den roten Wein, bitte", blank: "vino" },
  { it: "Prendo una birra per favore", de: "Ich nehme ein Bier, bitte", blank: "birra" },
  { it: "Voglio una birra fredda per favore", de: "Ich will ein kaltes Bier, bitte", blank: "birra" },
  { it: "Voglio un bicchiere di latte", de: "Ich will ein Glas Milch", blank: "latte" },
  { it: "Prendo il latte caldo per favore", de: "Ich nehme die warme Milch, bitte", blank: "latte" },
];

// The keeper's half of it. Short enough to read at a glance over a canvas, and
// every one of them a word the game teaches, so the exchange is comprehensible
// rather than decoration: he greets, he takes the order, and when the wrong word
// is tapped he simply doesn't understand — the order is not lost, it is asked
// again, because a shrug is the feedback and a closed screen would be a
// punishment.
const BAR_KEEPER = {
  greet: [
    { it: "Buonasera!", de: "Guten Abend!" },
    { it: "Che prendi?", de: "Was nimmst du?" },
    { it: "Ecco il menù!", de: "Hier ist die Speisekarte!" },
  ],
  serve: [
    { it: "Subito!", de: "Sofort!" },
    { it: "Volentieri!", de: "Gerne!" },
    { it: "Certo!", de: "Sicher!" },
    { it: "Ecco!", de: "Hier, bitte!" },
  ],
  puzzled: [
    { it: "Come?", de: "Wie bitte?" },
    { it: "Che?", de: "Was?" },
  ],
  thanks: { it: "Grazie!", de: "Danke!" },
};

// Blank words grouped by part of speech, so fill-in distractors match the
// answer's kind of word (deduped once at load).
const BLANKS_BY_POS = (() => {
  const acc = {};
  for (const s of SENTENCE_POOL) (acc[s.pos] ||= []).push(s.blank);
  for (const k in acc) acc[k] = [...new Set(acc[k])];
  return acc;
})();

// Content-word pool used to pad the "build the sentence" word bank with a
// couple of plausible wrong tiles (all real words from the sentence corpus).
const SENTENCE_WORDS = [
  ...new Set(SENTENCE_POOL.flatMap((s) => s.it.split(" ").filter((w) => w.length > 2))),
];

// ---------------------------------------------------------------------------
// Conjugation — the present tense (presente indicativo) of the pool's verbs.
// This is what the conjugation exercises drill (see quiz.js): from picking one
// form out of four, up to writing the whole paradigm out from nothing.
//
// The six persons, in the order every table in the game lists them. `de` is the
// German pronoun the learner reads the row as; a slash means the one Italian
// form covers both German ones.
// ---------------------------------------------------------------------------
const CONJ_PERSONS = [
  { it: "io", de: "ich" },
  { it: "tu", de: "du" },
  { it: "lui / lei", de: "er / sie" },
  { it: "noi", de: "wir" },
  { it: "voi", de: "ihr" },
  { it: "loro", de: "sie (Pl.)" },
];

// The three regular classes plus -isc-: verbs like capire that wedge -isc- into
// the singular and the third person plural, which is a class of its own to a
// learner even though the grammar books file it under -ire.
const CONJ_ENDINGS = {
  are: ["o", "i", "a", "iamo", "ate", "ano"],
  ere: ["o", "i", "e", "iamo", "ete", "ono"],
  ire: ["o", "i", "e", "iamo", "ite", "ono"],
  isc: ["isco", "isci", "isce", "iamo", "ite", "iscono"],
};

// A regular verb's six forms, built from the stem so the pattern stays a pattern
// (adding a regular verb below is one line, and it cannot disagree with itself).
// Two spelling rules keep the written form honest about the sound:
//  · -care/-gare grow an h before an i-ending, so the c/g stays hard
//    (giocare → giochi, not *gioci)
//  · -iare has only ever one i, so the stem's i is swallowed by an i-ending
//    (mangiare → mangi / mangiamo, not *mangii / *mangiiamo)
function conjugateRegular(inf, group) {
  const stem = inf.slice(0, -3);
  return CONJ_ENDINGS[group].map((end) => {
    if (group === "are" && /[cg]$/.test(stem) && end[0] === "i") return stem + "h" + end;
    if (stem.endsWith("i") && end[0] === "i") return stem + end.slice(1);
    return stem + end;
  });
}

// The verbs the drills draw from. `group` is the class its forms are built from;
// `irr` means the six forms are written out here because nothing generates them.
// Everything except the -isc- block also lives in WORD_POOL, so a conjugation
// answer is tallied against the same verb the rune circle teaches.
const CONJ_POOL = [
  // -are
  { it: "parlare", de: "sprechen", group: "are" },
  { it: "mangiare", de: "essen", group: "are" },
  { it: "amare", de: "lieben", group: "are" },
  { it: "giocare", de: "spielen", group: "are" },
  { it: "lavorare", de: "arbeiten", group: "are" },
  { it: "studiare", de: "lernen", group: "are" },
  { it: "comprare", de: "kaufen", group: "are" },
  { it: "guardare", de: "schauen", group: "are" },
  { it: "ascoltare", de: "zuhören", group: "are" },
  { it: "camminare", de: "laufen", group: "are" },
  { it: "pensare", de: "denken", group: "are" },
  { it: "trovare", de: "finden", group: "are" },
  { it: "chiamare", de: "rufen", group: "are" },
  { it: "aspettare", de: "warten", group: "are" },
  { it: "arrivare", de: "ankommen", group: "are" },
  { it: "pagare", de: "bezahlen", group: "are" },
  { it: "cucinare", de: "kochen", group: "are" },
  // -ere
  { it: "leggere", de: "lesen", group: "ere" },
  { it: "scrivere", de: "schreiben", group: "ere" },
  { it: "vedere", de: "sehen", group: "ere" },
  { it: "prendere", de: "nehmen", group: "ere" },
  { it: "correre", de: "rennen", group: "ere" },
  { it: "vivere", de: "leben", group: "ere" },
  { it: "chiudere", de: "schließen", group: "ere" },
  // -ire
  { it: "dormire", de: "schlafen", group: "ire" },
  { it: "sentire", de: "hören", group: "ire" },
  { it: "aprire", de: "öffnen", group: "ire" },
  { it: "partire", de: "abfahren", group: "ire" },
  // -ire with -isc-
  { it: "capire", de: "verstehen", group: "isc" },
  { it: "finire", de: "beenden", group: "isc" },
  { it: "preferire", de: "bevorzugen", group: "isc" },
  { it: "pulire", de: "putzen", group: "isc" },
  // irregular — the everyday verbs, which are exactly the ones that misbehave
  { it: "essere", de: "sein", group: "irr", forms: ["sono", "sei", "è", "siamo", "siete", "sono"] },
  { it: "avere", de: "haben", group: "irr", forms: ["ho", "hai", "ha", "abbiamo", "avete", "hanno"] },
  { it: "fare", de: "machen", group: "irr", forms: ["faccio", "fai", "fa", "facciamo", "fate", "fanno"] },
  { it: "andare", de: "gehen", group: "irr", forms: ["vado", "vai", "va", "andiamo", "andate", "vanno"] },
  { it: "venire", de: "kommen", group: "irr", forms: ["vengo", "vieni", "viene", "veniamo", "venite", "vengono"] },
  { it: "stare", de: "bleiben", group: "irr", forms: ["sto", "stai", "sta", "stiamo", "state", "stanno"] },
  { it: "dare", de: "geben", group: "irr", forms: ["do", "dai", "dà", "diamo", "date", "danno"] },
  { it: "dire", de: "sagen", group: "irr", forms: ["dico", "dici", "dice", "diciamo", "dite", "dicono"] },
  { it: "bere", de: "trinken", group: "irr", forms: ["bevo", "bevi", "beve", "beviamo", "bevete", "bevono"] },
  { it: "uscire", de: "hinausgehen", group: "irr", forms: ["esco", "esci", "esce", "usciamo", "uscite", "escono"] },
  { it: "sapere", de: "wissen", group: "irr", forms: ["so", "sai", "sa", "sappiamo", "sapete", "sanno"] },
  { it: "potere", de: "können", group: "irr", forms: ["posso", "puoi", "può", "possiamo", "potete", "possono"] },
  { it: "volere", de: "wollen", group: "irr", forms: ["voglio", "vuoi", "vuole", "vogliamo", "volete", "vogliono"] },
  { it: "dovere", de: "müssen", group: "irr", forms: ["devo", "devi", "deve", "dobbiamo", "dovete", "devono"] },
].map((v) => ({ ...v, forms: v.forms || conjugateRegular(v.it, v.group) }));

Object.assign(window.Incanto, {
  WORD_POOL, SENTENCE_POOL, SENTENCE_WORDS, BLANKS_BY_POS,
  BAR_ITEMS, BAR_ORDER_POOL, BAR_KEEPER,
  CONJ_PERSONS, CONJ_ENDINGS, CONJ_POOL, conjugateRegular,
});
