"use strict";
// ==============================================================================
// content.js — vocabulary + sentence data. Owns: WORD_POOL, SENTENCE_POOL,
// BLANKS_BY_POS, SENTENCE_WORDS. Edit here to add/adjust vocab.
// ==============================================================================

// ---------------------------------------------------------------------------
// Word pool — the A1 (beginner) Italian vocabulary, drawn in order and cycled.
// Each entry pairs the Italian word (`it`, shown in the circle) with its German
// meaning (`de`). Nouns keep their article in both languages so the learner
// absorbs gender; verbs are given as infinitives, everything else in its base
// form. Grouped by theme for upkeep; the game treats it as one flat list.
// ---------------------------------------------------------------------------
const WORD_POOL = [
  // Greetings & courtesy
  { it: "ciao", de: "hallo" },
  { it: "buongiorno", de: "guten Morgen" },
  { it: "buonasera", de: "guten Abend" },
  { it: "buonanotte", de: "gute Nacht" },
  { it: "arrivederci", de: "auf Wiedersehen" },
  { it: "grazie", de: "danke" },
  { it: "prego", de: "gern geschehen" },
  { it: "per favore", de: "bitte" },
  { it: "scusa", de: "Entschuldigung" },
  { it: "sì", de: "ja" },

  // People & family
  { it: "la famiglia", de: "die Familie" },
  { it: "la madre", de: "die Mutter" },
  { it: "il padre", de: "der Vater" },
  { it: "il figlio", de: "der Sohn" },
  { it: "la figlia", de: "die Tochter" },
  { it: "il fratello", de: "der Bruder" },
  { it: "la sorella", de: "die Schwester" },
  { it: "il nonno", de: "der Großvater" },
  { it: "la nonna", de: "die Großmutter" },
  { it: "il bambino", de: "das Kind" },
  { it: "l'uomo", de: "der Mann" },
  { it: "la donna", de: "die Frau" },
  { it: "l'amico", de: "der Freund" },
  { it: "il ragazzo", de: "der Junge" },
  { it: "la ragazza", de: "das Mädchen" },
  { it: "il nome", de: "der Name" },

  // Body
  { it: "la testa", de: "der Kopf" },
  { it: "la faccia", de: "das Gesicht" },
  { it: "la mano", de: "die Hand" },
  { it: "il piede", de: "der Fuß" },
  { it: "l'occhio", de: "das Auge" },
  { it: "la bocca", de: "der Mund" },
  { it: "il naso", de: "die Nase" },
  { it: "l'orecchio", de: "das Ohr" },
  { it: "il braccio", de: "der Arm" },
  { it: "la gamba", de: "das Bein" },
  { it: "il cuore", de: "das Herz" },
  { it: "i capelli", de: "die Haare" },
  { it: "il dente", de: "der Zahn" },

  // Food & drink
  { it: "il cibo", de: "das Essen" },
  { it: "il pane", de: "das Brot" },
  { it: "l'acqua", de: "das Wasser" },
  { it: "il vino", de: "der Wein" },
  { it: "il latte", de: "die Milch" },
  { it: "il caffè", de: "der Kaffee" },
  { it: "il tè", de: "der Tee" },
  { it: "la birra", de: "das Bier" },
  { it: "la frutta", de: "das Obst" },
  { it: "la mela", de: "der Apfel" },
  { it: "l'arancia", de: "die Orange" },
  { it: "il formaggio", de: "der Käse" },
  { it: "la carne", de: "das Fleisch" },
  { it: "il pesce", de: "der Fisch" },
  { it: "l'uovo", de: "das Ei" },
  { it: "il riso", de: "der Reis" },
  { it: "il sale", de: "das Salz" },
  { it: "lo zucchero", de: "der Zucker" },
  { it: "la verdura", de: "das Gemüse" },
  { it: "il pollo", de: "das Hähnchen" },
  { it: "il gelato", de: "das Eis" },
  { it: "il burro", de: "die Butter" },
  { it: "il dolce", de: "der Nachtisch" },
  { it: "la colazione", de: "das Frühstück" },
  { it: "il pranzo", de: "das Mittagessen" },
  { it: "la cena", de: "das Abendessen" },

  // Animals
  { it: "il gatto", de: "die Katze" },
  { it: "il cane", de: "der Hund" },
  { it: "il cavallo", de: "das Pferd" },
  { it: "l'uccello", de: "der Vogel" },
  { it: "la mucca", de: "die Kuh" },
  { it: "il topo", de: "die Maus" },
  { it: "il maiale", de: "das Schwein" },
  { it: "la pecora", de: "das Schaf" },

  // Home & objects
  { it: "la casa", de: "das Haus" },
  { it: "la porta", de: "die Tür" },
  { it: "la finestra", de: "das Fenster" },
  { it: "la sedia", de: "der Stuhl" },
  { it: "il tavolo", de: "der Tisch" },
  { it: "il letto", de: "das Bett" },
  { it: "la cucina", de: "die Küche" },
  { it: "il bagno", de: "das Badezimmer" },
  { it: "la camera", de: "das Zimmer" },
  { it: "la chiave", de: "der Schlüssel" },
  { it: "il libro", de: "das Buch" },
  { it: "la penna", de: "der Stift" },
  { it: "la carta", de: "das Papier" },
  { it: "la lampada", de: "die Lampe" },
  { it: "lo specchio", de: "der Spiegel" },
  { it: "il telefono", de: "das Telefon" },
  { it: "l'orologio", de: "die Uhr" },

  // Clothes
  { it: "il vestito", de: "das Kleid" },
  { it: "la scarpa", de: "der Schuh" },
  { it: "il cappello", de: "der Hut" },
  { it: "la giacca", de: "die Jacke" },
  { it: "i pantaloni", de: "die Hose" },
  { it: "la camicia", de: "das Hemd" },
  { it: "la borsa", de: "die Tasche" },

  // Nature
  { it: "il sole", de: "die Sonne" },
  { it: "la luna", de: "der Mond" },
  { it: "la stella", de: "der Stern" },
  { it: "il cielo", de: "der Himmel" },
  { it: "il mare", de: "das Meer" },
  { it: "la montagna", de: "der Berg" },
  { it: "il fiume", de: "der Fluss" },
  { it: "l'albero", de: "der Baum" },
  { it: "il fiore", de: "die Blume" },
  { it: "la pioggia", de: "der Regen" },
  { it: "la neve", de: "der Schnee" },
  { it: "il vento", de: "der Wind" },
  { it: "il fuoco", de: "das Feuer" },
  { it: "la terra", de: "die Erde" },
  { it: "il bosco", de: "der Wald" },
  { it: "la spiaggia", de: "der Strand" },

  // Time
  { it: "il giorno", de: "der Tag" },
  { it: "la notte", de: "die Nacht" },
  { it: "la mattina", de: "der Morgen" },
  { it: "la sera", de: "der Abend" },
  { it: "la settimana", de: "die Woche" },
  { it: "il mese", de: "der Monat" },
  { it: "l'anno", de: "das Jahr" },
  { it: "l'ora", de: "die Stunde" },
  { it: "il tempo", de: "die Zeit" },
  { it: "oggi", de: "heute" },
  { it: "domani", de: "morgen" },
  { it: "ieri", de: "gestern" },
  { it: "adesso", de: "jetzt" },
  { it: "sempre", de: "immer" },
  { it: "mai", de: "nie" },
  { it: "presto", de: "früh" },
  { it: "tardi", de: "spät" },

  // Days of the week
  { it: "lunedì", de: "Montag" },
  { it: "martedì", de: "Dienstag" },
  { it: "mercoledì", de: "Mittwoch" },
  { it: "giovedì", de: "Donnerstag" },
  { it: "venerdì", de: "Freitag" },
  { it: "sabato", de: "Samstag" },
  { it: "domenica", de: "Sonntag" },

  // Colours
  { it: "rosso", de: "rot" },
  { it: "blu", de: "blau" },
  { it: "verde", de: "grün" },
  { it: "giallo", de: "gelb" },
  { it: "nero", de: "schwarz" },
  { it: "bianco", de: "weiß" },
  { it: "grigio", de: "grau" },
  { it: "rosa", de: "rosa" },
  { it: "arancione", de: "orange" },
  { it: "marrone", de: "braun" },

  // Numbers
  { it: "uno", de: "eins" },
  { it: "due", de: "zwei" },
  { it: "tre", de: "drei" },
  { it: "quattro", de: "vier" },
  { it: "cinque", de: "fünf" },
  { it: "sei", de: "sechs" },
  { it: "sette", de: "sieben" },
  { it: "otto", de: "acht" },
  { it: "nove", de: "neun" },
  { it: "dieci", de: "zehn" },

  // Adjectives
  { it: "grande", de: "groß" },
  { it: "piccolo", de: "klein" },
  { it: "buono", de: "gut" },
  { it: "cattivo", de: "schlecht" },
  { it: "bello", de: "schön" },
  { it: "brutto", de: "hässlich" },
  { it: "nuovo", de: "neu" },
  { it: "vecchio", de: "alt" },
  { it: "caldo", de: "heiß" },
  { it: "freddo", de: "kalt" },
  { it: "alto", de: "hoch" },
  { it: "basso", de: "niedrig" },
  { it: "lungo", de: "lang" },
  { it: "corto", de: "kurz" },
  { it: "facile", de: "einfach" },
  { it: "difficile", de: "schwierig" },
  { it: "felice", de: "glücklich" },
  { it: "triste", de: "traurig" },
  { it: "veloce", de: "schnell" },
  { it: "lento", de: "langsam" },
  { it: "forte", de: "stark" },
  { it: "debole", de: "schwach" },
  { it: "giovane", de: "jung" },
  { it: "ricco", de: "reich" },
  { it: "povero", de: "arm" },
  { it: "pieno", de: "voll" },
  { it: "vuoto", de: "leer" },
  { it: "pulito", de: "sauber" },
  { it: "sporco", de: "schmutzig" },

  // Verbs
  { it: "essere", de: "sein" },
  { it: "avere", de: "haben" },
  { it: "fare", de: "machen" },
  { it: "andare", de: "gehen" },
  { it: "venire", de: "kommen" },
  { it: "stare", de: "bleiben" },
  { it: "mangiare", de: "essen" },
  { it: "bere", de: "trinken" },
  { it: "dormire", de: "schlafen" },
  { it: "parlare", de: "sprechen" },
  { it: "dire", de: "sagen" },
  { it: "leggere", de: "lesen" },
  { it: "scrivere", de: "schreiben" },
  { it: "vedere", de: "sehen" },
  { it: "sentire", de: "hören" },
  { it: "capire", de: "verstehen" },
  { it: "sapere", de: "wissen" },
  { it: "volere", de: "wollen" },
  { it: "potere", de: "können" },
  { it: "dovere", de: "müssen" },
  { it: "vivere", de: "leben" },
  { it: "amare", de: "lieben" },
  { it: "giocare", de: "spielen" },
  { it: "lavorare", de: "arbeiten" },
  { it: "studiare", de: "lernen" },
  { it: "comprare", de: "kaufen" },
  { it: "aprire", de: "öffnen" },
  { it: "chiudere", de: "schließen" },
  { it: "guardare", de: "schauen" },
  { it: "ascoltare", de: "zuhören" },
  { it: "camminare", de: "laufen" },
  { it: "correre", de: "rennen" },
  { it: "pensare", de: "denken" },
  { it: "prendere", de: "nehmen" },
  { it: "dare", de: "geben" },
  { it: "trovare", de: "finden" },
  { it: "chiamare", de: "rufen" },
  { it: "aspettare", de: "warten" },
  { it: "arrivare", de: "ankommen" },
  { it: "partire", de: "abfahren" },
  { it: "pagare", de: "bezahlen" },
  { it: "cucinare", de: "kochen" },

  // Places
  { it: "la città", de: "die Stadt" },
  { it: "il paese", de: "das Land" },
  { it: "la strada", de: "die Straße" },
  { it: "la scuola", de: "die Schule" },
  { it: "il negozio", de: "das Geschäft" },
  { it: "il ristorante", de: "das Restaurant" },
  { it: "l'ospedale", de: "das Krankenhaus" },
  { it: "la stazione", de: "der Bahnhof" },
  { it: "l'aeroporto", de: "der Flughafen" },
  { it: "la banca", de: "die Bank" },
  { it: "il parco", de: "der Park" },
  { it: "la chiesa", de: "die Kirche" },
  { it: "il mercato", de: "der Markt" },
  { it: "l'ufficio", de: "das Büro" },
  { it: "il museo", de: "das Museum" },
  { it: "la piazza", de: "der Platz" },

  // Transport
  { it: "la macchina", de: "das Auto" },
  { it: "il treno", de: "der Zug" },
  { it: "l'autobus", de: "der Bus" },
  { it: "la bicicletta", de: "das Fahrrad" },
  { it: "l'aereo", de: "das Flugzeug" },
  { it: "la nave", de: "das Schiff" },

  // Everyday life
  { it: "il lavoro", de: "die Arbeit" },
  { it: "i soldi", de: "das Geld" },
  { it: "il regalo", de: "das Geschenk" },
  { it: "la festa", de: "die Party" },
  { it: "la musica", de: "die Musik" },
  { it: "il film", de: "der Film" },
  { it: "la parola", de: "das Wort" },
  { it: "la lingua", de: "die Sprache" },
  { it: "il numero", de: "die Zahl" },
  { it: "la domanda", de: "die Frage" },
  { it: "la risposta", de: "die Antwort" },
  { it: "il problema", de: "das Problem" },
  { it: "l'idea", de: "die Idee" },
  { it: "la vita", de: "das Leben" },
  { it: "l'amore", de: "die Liebe" },
  { it: "la storia", de: "die Geschichte" },
  { it: "il colore", de: "die Farbe" },

  // Question & function words
  { it: "chi", de: "wer" },
  { it: "che", de: "was" },
  { it: "dove", de: "wo" },
  { it: "quando", de: "wann" },
  { it: "perché", de: "warum" },
  { it: "come", de: "wie" },
  { it: "quanto", de: "wie viel" },
  { it: "molto", de: "sehr" },
  { it: "poco", de: "wenig" },
  { it: "tutto", de: "alles" },
  { it: "niente", de: "nichts" },
  { it: "qui", de: "hier" },
  { it: "là", de: "dort" },
  { it: "bene", de: "gut" },
  { it: "male", de: "schlecht" },
  { it: "anche", de: "auch" },
  { it: "ma", de: "aber" },
  { it: "con", de: "mit" },
  { it: "senza", de: "ohne" },
  { it: "sotto", de: "unter" },
  { it: "sopra", de: "über" },
  { it: "dentro", de: "drinnen" },
  { it: "fuori", de: "draußen" },
  { it: "vicino", de: "nah" },
  { it: "lontano", de: "weit" },
];

// ---------------------------------------------------------------------------
// Sentence pool — short A1 Italian sentences with their German translation.
// These feed the "fill the blank" and "build the sentence" quiz exercises.
// `it` is the Italian sentence (tokens split on spaces), `de` its German
// meaning (shown as a hint), `blank` the single Italian token that gets removed
// for fill-in exercises, and `pos` its part of speech so that the multiple-
// choice distractors stay the same kind of word (noun/adj/verb) as the answer.
// ---------------------------------------------------------------------------
const SENTENCE_POOL = [
  { it: "Io bevo il caffè", de: "Ich trinke den Kaffee", blank: "caffè", pos: "noun" },
  { it: "Tu mangi il pane", de: "Du isst das Brot", blank: "pane", pos: "noun" },
  { it: "La mela è rossa", de: "Der Apfel ist rot", blank: "mela", pos: "noun" },
  { it: "Il cane è grande", de: "Der Hund ist groß", blank: "cane", pos: "noun" },
  { it: "La casa è bianca", de: "Das Haus ist weiß", blank: "casa", pos: "noun" },
  { it: "Beviamo molta acqua", de: "Wir trinken viel Wasser", blank: "acqua", pos: "noun" },
  { it: "Il bambino ha fame", de: "Das Kind hat Hunger", blank: "bambino", pos: "noun" },
  { it: "La madre legge un libro", de: "Die Mutter liest ein Buch", blank: "libro", pos: "noun" },
  { it: "Il padre lavora oggi", de: "Der Vater arbeitet heute", blank: "padre", pos: "noun" },
  { it: "Mangio una mela", de: "Ich esse einen Apfel", blank: "mela", pos: "noun" },
  { it: "Il vino è buono", de: "Der Wein ist gut", blank: "vino", pos: "noun" },
  { it: "La sorella ha un gatto", de: "Die Schwester hat eine Katze", blank: "gatto", pos: "noun" },
  { it: "Il fratello beve il tè", de: "Der Bruder trinkt den Tee", blank: "tè", pos: "noun" },
  { it: "La nonna fa il pane", de: "Die Großmutter macht das Brot", blank: "pane", pos: "noun" },
  { it: "Il pesce nuota nel mare", de: "Der Fisch schwimmt im Meer", blank: "pesce", pos: "noun" },
  { it: "Noi mangiamo il formaggio", de: "Wir essen den Käse", blank: "formaggio", pos: "noun" },
  { it: "La donna beve il vino", de: "Die Frau trinkt den Wein", blank: "vino", pos: "noun" },
  { it: "Ho un amico italiano", de: "Ich habe einen italienischen Freund", blank: "amico", pos: "noun" },
  { it: "La città è grande", de: "Die Stadt ist groß", blank: "città", pos: "noun" },
  { it: "Il libro è nuovo", de: "Das Buch ist neu", blank: "libro", pos: "noun" },
  { it: "Mangiamo la frutta", de: "Wir essen das Obst", blank: "frutta", pos: "noun" },
  { it: "Il latte è freddo", de: "Die Milch ist kalt", blank: "latte", pos: "noun" },
  { it: "La casa ha una porta", de: "Das Haus hat eine Tür", blank: "porta", pos: "noun" },
  { it: "Il gatto dorme", de: "Die Katze schläft", blank: "gatto", pos: "noun" },
  { it: "La ragazza è felice", de: "Das Mädchen ist glücklich", blank: "felice", pos: "adj" },
  { it: "Il ragazzo corre veloce", de: "Der Junge läuft schnell", blank: "veloce", pos: "adj" },
  { it: "Il caffè è caldo", de: "Der Kaffee ist heiß", blank: "caldo", pos: "adj" },
  { it: "La neve è bianca", de: "Der Schnee ist weiß", blank: "bianca", pos: "adj" },
  { it: "Il mare è grande", de: "Das Meer ist groß", blank: "grande", pos: "adj" },
  { it: "Oggi fa freddo", de: "Heute ist es kalt", blank: "freddo", pos: "adj" },
  { it: "Il cane mangia la carne", de: "Der Hund isst das Fleisch", blank: "mangia", pos: "verb" },
  { it: "La donna legge il libro", de: "Die Frau liest das Buch", blank: "legge", pos: "verb" },
  { it: "Noi beviamo il latte", de: "Wir trinken die Milch", blank: "beviamo", pos: "verb" },
  { it: "Il bambino dorme molto", de: "Das Kind schläft viel", blank: "dorme", pos: "verb" },
];

// Blank words grouped by part of speech, so fill-in distractors match the
// answer's kind of word (deduped once at load).
const BLANKS_BY_POS = (() => {
  const acc = {};
  for (const s of SENTENCE_POOL) (acc[s.pos] ||= []).push(s.blank);
  for (const k in acc) acc[k] = [...new Set(acc[k])];
  return acc;
})();

// Content-word pool used to pad the "build the sentence" word bank with a
// couple of plausible wrong tiles (all real words from the sentence corpus).
const SENTENCE_WORDS = [
  ...new Set(SENTENCE_POOL.flatMap((s) => s.it.split(" ").filter((w) => w.length > 2))),
];

Object.assign(window.Incanto, { WORD_POOL, SENTENCE_POOL, SENTENCE_WORDS, BLANKS_BY_POS });
